### ISSUE TITLE
Doesn't gyp build with yarn

### ISSUE THREAD

**Issue by scriptjs** [justadudewhohacks/opencv4nodejs#100]
A yarn build with gyp doesn't work with this package. It works with npm however. I've replaced my home dir in traceback with `/project/path` below:

```
error /project/path/node_modules/opencv4nodejs: Command failed.
Exit code: 7
Command: node-gyp rebuild
Arguments: 
Directory: /project/path/node_modules/opencv4nodejs
Output:
gyp ERR! UNCAUGHT EXCEPTION 
gyp ERR! stack Error: Cannot find module 'har-validator'
gyp ERR! stack     at Function.Module._resolveFilename (module.js:489:15)
gyp ERR! stack     at Function.Module._load (module.js:439:25)
gyp ERR! stack     at Module.require (module.js:517:17)
gyp ERR! stack     at require (internal/module.js:11:18)
gyp ERR! stack     at Object.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/request/lib/har.js:5:16)
gyp ERR! stack     at Module._compile (module.js:573:30)
gyp ERR! stack     at Object.Module._extensions..js (module.js:584:10)
gyp ERR! stack     at Module.load (module.js:507:32)
gyp ERR! stack     at tryModuleLoad (module.js:470:12)
gyp ERR! stack     at Function.Module._load (module.js:462:3)
gyp ERR! System Darwin 16.7.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /project/path/node_modules/opencv4nodejs
gyp ERR! node -v v8.4.0
gyp ERR! node-gyp -v v3.6.2
```

**Comment by justadudewhohacks** [comment]
Are you sure that this is not related to any of your dependencies? I have no trouble installing opencv4nodejs with yarn.

Also the module 'har-validator' which it throws an error for is not a dependency of opencv4nodejs. Maybe there is a corrupt yarn.lock file dangling arround in your projects directory?

**Comment by scriptjs** [comment]
Hi, thanks. I'll do some further checking and get back.

**Comment by scriptjs** [comment]
Hi. I've updated my node and cleared my node_modules and rebuilt with yarn and its all good. Apologies for the noise.
