### ISSUE TITLE
Problem with require opencv4nodejs

### ISSUE THREAD

**Issue by Gektor40k** [justadudewhohacks/opencv4nodejs#109]
I apologize if this question has already been answered somewhere, but I can not solve my problem. When  run "const cv = require ('opencv4nodejs');" I have an error in the console: 
module.js:597
  return process.dlopen(module, path._makeLong(filename));
                 ^
Error: The specified module could not be found.
\\?\D:\sources\nodejs\_T2\node_modules\opencv4nodejs\build\Release\opencv4nodejs.node
    at Error (native)
    at Object.Module._extensions..node (module.js:597:18)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (D:\sources\nodejs\_T2\node_modules\opencv4nodejs\lib\opencv4nodejs.js:7:8)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)

I do not know what to do. looks like does not have any .dll.
OpenCV 3.3.1 is inctalled, maked environment variables, all by instructions, 
I hope for your help.

**Comment by justadudewhohacks** [comment]
Hey,
this error message means you are missing the path to the OpenCV binaries (.dlls) in your system path.
See #50, #106.

**Comment by Gektor40k** [comment]
Thank you so much! I'll go learn "how to google" at the same time ;D I apologize for wasted time

**Comment by justadudewhohacks** [comment]
No problem!
