### ISSUE TITLE
install error

### ISSUE THREAD

**Issue by xiaowuming** [justadudewhohacks/opencv4nodejs#121]
Error: lib for module 'imgcodecs' not found in OPENCV_LIB_DIR ('/usr/local/lib')
    at modules.forEach.m (/Users/songxi/work/github/test/node_modules/opencv4nodejs/lib/utils.js:105:15)
    at Array.forEach (<anonymous>)
    at fs.readdir (/Users/songxi/work/github/test/node_modules/opencv4nodejs/lib/utils.js:101:13)
    at FSReqWrap.oncomplete (fs.js:135:15)
gyp: Call to 'node ./lib/libs.js' returned exit status 1 while in binding.gyp. while trying to load binding.gyp
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:336:16)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
gyp ERR! System Darwin 16.7.0
gyp ERR! command "/usr/local/Cellar/node/8.9.0/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/songxi/work/github/test/node_modules/opencv4nodejs
gyp ERR! node -v v8.9.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
npm WARN enoent ENOENT: no such file or directory, open '/Users/songxi/work/github/test/package.json'
npm WARN test No description
npm WARN test No repository field.
npm WARN test No README data
npm WARN test No license field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! opencv4nodejs@2.28.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the opencv4nodejs@2.28.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:

**Comment by leejh3224** [comment]
Have you checked for OpenCV installed locally on your machine?

If not, you should download OpenCV library first to download this module. 

In case you are using osx(mac), you can download it via homebrew. 

Type this in your terminal.

`brew tap homebrew/science`
`brew install opencv`

This would bring you the newest version of OpenCV(v 3.4).

 And then try adding this module again.

Hope this would help, xiaowuming!

**Comment by justadudewhohacks** [comment]
Closing because of inactivity. If the problem remains, feel free to reopen.
