### ISSUE TITLE
How to solve this problem:Cannot find module '../build/Release/opencv4nodejs'

### ISSUE THREAD

**Issue by 4qing** [justadudewhohacks/opencv4nodejs#223]
When I use it in electron, I run "electron-rebuild -w opencv4nodejs" and return "rebuild complete".But when i import and run,the problem occured:
```
App threw an error during load
Error: Cannot find module '../build/Release/opencv4nodejs'
    at Module._resolveFilename (module.js:485:15)
    at Function.Module._resolveFilename (D:\projects\fr_electron\node_modules\_electron@1.8.4@electron\dist\resources\electron.asar\common\reset-search-paths.js:35:12)
    at Function.Module._load (module.js:437:25)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (D:\projects\fr_electron\node_modules\_opencv4nodejs@3.5.0@opencv4nodejs\lib\opencv4nodejs.js:16:8)
    at Object.<anonymous> (D:\projects\fr_electron\node_modules\_opencv4nodejs@3.5.0@opencv4nodejs\lib\opencv4nodejs.js:34:3)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32
```

**Comment by 4qing** [comment]
I don't use anything...

**Comment by justadudewhohacks** [comment]
Can you give some more information then? Have you tried the other opencv-electron example, without webpack?

**Comment by 4qing** [comment]
Thanks a lot! I delete my project and create a new one .It works well.Maybe the first time it doesn't install opencv successfully.

**Comment by rahshel94** [comment]
I am having this same issue in my project (using electron, webpack, and vue). I have looked at the webpack/react example, but I've found that I get a similar error when trying to run it:
```
App threw an error during load
Error: Cannot find module '../renderer/node_modules/opencv-build'
    at Module._resolveFilename (module.js:485:15)
    at Function.Module._resolveFilename (C:\Users\rahshel\opencv-electron\webpack-reactjs\node_modules\electron\dist\resources\electron.asar\common\reset-search-paths.js:35:12)
    at Function.Module._load (module.js:437:25)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\Users\rahshel\opencv-electron\webpack-reactjs\main\main.js:5:29)
    at Object.<anonymous> (C:\Users\rahshel\opencv-electron\webpack-reactjs\main\main.js:49:3)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
```

**Comment by snakelecaps** [comment]
Hello guys, Im having the same issue... installation was okay but i always have 
`Error: Cannot find module 'opencv4nodejs' `

**Comment by droidMakk** [comment]
I'm receiving a similar issue while trying to import in nodejs project.
`const cv = require('opencv4nodejs')`;

It runs fine in windows. But in Linux I'm receiving issues.
> Cannot find module '/.../node_modules/opencv4nodejs/build/Release/opencv4nodejs'

**Comment by sajithgr** [comment]
hai guys ,

please suggest any workaround for this issue:
[debug] [35m[Support][39m \\?\C:\Users\******\AppData\Roaming\npm\node_modules\opencv4nodejs\build\Release\opencv4nodejs.node
[debug] [35m[Support][39m Failed to load global package 'opencv4nodejs': The "path" argument must be of type string. Received type undefined

opencvnode4js installaion was suceess with no issues, but appium cant load the module
-----------
windows 10
appium 1.18.0
opencv4nodejs@5.6.0

**Comment by younthu** [comment]
Same here. mac, electron 13.0.1
