### ISSUE TITLE
is it working on windows? Specs node 8.11,7 windows7

### ISSUE THREAD

**Issue by partizanos** [justadudewhohacks/opencv4nodejs#306]
I run npm install and get the following:

````
\opencv4nodejs\node_modules\opencv-build
> node ./install.js

info install if you want to use an own OpenCV installation set OPENCV4NODEJS_DISABLE_AUTOBUILD
info install running install script...
ERR! Error: Command failed: cmake --version
'cmake' is not recognized as an internal or external command,
operable program or batch file.`

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! opencv-build@0.0.12 install: `node ./install.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the opencv-build@0.0.12 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:`

```


##################At npm/debug log it sais:

`820 verbose stack Error: opencv-build@0.0.12 install: `node ./install.js`
820 verbose stack Exit status 1
820 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\index.js:285:16)
820 verbose stack     at emitTwo (events.js:126:13)
820 verbose stack     at EventEmitter.emit (events.js:214:7)
820 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
820 verbose stack     at emitTwo (events.js:126:13)
820 verbose stack     at ChildProcess.emit (events.js:214:7)
820 verbose stack     at maybeClose (internal/child_process.js:925:16)
820 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
821 verbose pkgid opencv-build@0.0.12`

**Comment by 2Drcome333** [comment]
I am facing the same problem. Have you solved it?

**Comment by arjun-kava** [comment]
cmake is needed to compile source, install it from [https://cmake.org/install/](https://cmake.org/install/)
