### ISSUE TITLE
i cant run example

### ISSUE THREAD

**Issue by girs1982** [justadudewhohacks/opencv4nodejs#324]
root@gansta-System-Product-Name:~/Downloads/myface/js/opencv4nodejs/examples# node facemark.js
module.js:549
    throw err;
    ^

Error: Cannot find module '/home/gansta/Downloads/myface/js/opencv4nodejs/build/Release/opencv4nodejs'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/gansta/Downloads/myface/js/opencv4nodejs/lib/cv.js:17:8)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)

**Comment by justadudewhohacks** [comment]
This probably indicates, that the package wasn't built correctly (opencv4nodejs.node should be located at the path printed) or runtime libraries are not linked correctly, but in this case the error would be thrown during `process.dlopen`.

Are you using your own build or the auto build?

**Comment by girs1982** [comment]
automatic build

**Comment by justadudewhohacks** [comment]
Did it build successfully?

**Comment by girs1982** [comment]
yes no errors

**Comment by justadudewhohacks** [comment]
Odd, you could try requiring the `opencv4nodejs.node` file directly by providing the absolute path to that file.

**Comment by girs1982** [comment]
were it?

**Comment by wbern** [comment]
Understood, feel free to re-open the issue whenever.

**Comment by snakelecaps** [comment]
Sorry @justadudewhohacks  Im having the same issue. Im getting crazy with this error since yesterday. Where is the `opencv4nodejs.node` file ?

**Comment by girs1982** [comment]
it low internet connection for aws
