### ISSUE TITLE
opencv4nodejs fail to install with Auto build

### ISSUE THREAD

**Issue by George35mk** [justadudewhohacks/opencv4nodejs#361]
opencv4nodejs is not installed 

# Please make a video on youtube how to install your module with both methods, Manual and Auto

I have
-  OS: Windows 10
- Node: v8.11.3
- I have used vscode, PowerShell

I run multiple different combinations but none of them work

### I run this:

- npm install --save opencv4nodejs 

### After 1 hour of building with cmake I get this error.

![1](https://user-images.githubusercontent.com/20750445/43039902-b7a637c2-8d3f-11e8-8179-bdb07d2f3ee4.PNG)
![2](https://user-images.githubusercontent.com/20750445/43039904-bba44062-8d3f-11e8-8e1a-dbab6dd86a68.PNG)

```cmd
c:\users\giorg\documents\development\my repositories\electron-opencv\v2\node_modules\opencv4nodejs\cc\modules\xfeatures2d\SIFTDetector.h(2): f
atal error C1083: Cannot open include file: 'opencv2/xfeatures2d.hpp': No such file or directory (compiling source file ..\cc\modules\xfeature
s2d\xfeatures2d.cc) [C:\Users\giorg\Documents\Development\My repositories\electron-opencv\v2\node_modules\opencv4nodejs\build\opencv4nodejs.vc
xproj]
c:\users\giorg\documents\development\my repositories\electron-opencv\v2\node_modules\native-node-utils\src\AsyncWorker.h(30): warning C4996: '
Nan::Callback::Call': was declared deprecated (compiling source file ..\cc\modules\xfeatures2d\SIFTDetector.cc) [C:\Users\giorg\Documents\Deve
lopment\My repositories\electron-opencv\v2\node_modules\opencv4nodejs\build\opencv4nodejs.vcxproj]
  C:\Users\giorg\Documents\Development\My repositories\electron-opencv\v2\node_modules\nan\nan.h(1618): note: see declaration of 'Nan::Callbac
  k::Call' (compiling source file ..\cc\modules\xfeatures2d\SIFTDetector.cc)
c:\users\giorg\documents\development\my repositories\electron-opencv\v2\node_modules\native-node-utils\src\AsyncWorker.h(36): warning C4996: '
Nan::Callback::Call': was declared deprecated (compiling source file ..\cc\modules\xfeatures2d\SIFTDetector.cc) [C:\Users\giorg\Documents\Deve
lopment\My repositories\electron-opencv\v2\node_modules\opencv4nodejs\build\opencv4nodejs.vcxproj]
  C:\Users\giorg\Documents\Development\My repositories\electron-opencv\v2\node_modules\nan\nan.h(1618): note: see declaration of 'Nan::Callbac
  k::Call' (compiling source file ..\cc\modules\xfeatures2d\SIFTDetector.cc)
C:\Users\giorg\Documents\Development\My repositories\electron-opencv\v2\node_modules\native-node-utils\src\NativeNodeUtils.h(83): warning C499
6: 'Nan::Callback::Call': was declared deprecated (compiling source file ..\cc\modules\xfeatures2d\SIFTDetector.cc) [C:\Users\giorg\Documents\
Development\My repositories\electron-opencv\v2\node_modules\opencv4nodejs\build\opencv4nodejs.vcxproj]
  C:\Users\giorg\Documents\Development\My repositories\electron-opencv\v2\node_modules\nan\nan.h(1618): note: see declaration of 'Nan::Callbac
  k::Call' (compiling source file ..\cc\modules\xfeatures2d\SIFTDetector.cc)
c:\users\giorg\documents\development\my repositories\electron-opencv\v2\node_modules\opencv4nodejs\cc\modules\xfeatures2d\SIFTDetector.h(2): f
atal error C1083: Cannot open include file: 'opencv2/xfeatures2d.hpp': No such file or directory (compiling source file ..\cc\modules\xfeature
s2d\SIFTDetector.cc) [C:\Users\giorg\Documents\Development\My repositories\electron-opencv\v2\node_modules\opencv4nodejs\build\opencv4nodejs.v
cxproj]
c:\users\giorg\documents\development\my repositories\electron-opencv\v2\node_modules\native-node-utils\src\AsyncWorker.h(30): warning C4996: '
Nan::Callback::Call': was declared deprecated (compiling source file ..\cc\modules\xfeatures2d\SURFDetector.cc) [C:\Users\giorg\Documents\Deve
lopment\My repositories\electron-opencv\v2\node_modules\opencv4nodejs\build\opencv4nodejs.vcxproj]
  C:\Users\giorg\Documents\Development\My repositories\electron-opencv\v2\node_modules\nan\nan.h(1618): note: see declaration of 'Nan::Callbac
  k::Call' (compiling source file ..\cc\modules\xfeatures2d\SURFDetector.cc)
c:\users\giorg\documents\development\my repositories\electron-opencv\v2\node_modules\native-node-utils\src\AsyncWorker.h(36): warning C4996: '
Nan::Callback::Call': was declared deprecated (compiling source file ..\cc\modules\xfeatures2d\SURFDetector.cc) [C:\Users\giorg\Documents\Deve
lopment\My repositories\electron-opencv\v2\node_modules\opencv4nodejs\build\opencv4nodejs.vcxproj]
  C:\Users\giorg\Documents\Development\My repositories\electron-opencv\v2\node_modules\nan\nan.h(1618): note: see declaration of 'Nan::Callbac
  k::Call' (compiling source file ..\cc\modules\xfeatures2d\SURFDetector.cc)
C:\Users\giorg\Documents\Development\My repositories\electron-opencv\v2\node_modules\native-node-utils\src\NativeNodeUtils.h(83): warning C499
6: 'Nan::Callback::Call': was declared deprecated (compiling source file ..\cc\modules\xfeatures2d\SURFDetector.cc) [C:\Users\giorg\Documents\
Development\My repositories\electron-opencv\v2\node_modules\opencv4nodejs\build\opencv4nodejs.vcxproj]
  C:\Users\giorg\Documents\Development\My repositories\electron-opencv\v2\node_modules\nan\nan.h(1618): note: see declaration of 'Nan::Callbac
  k::Call' (compiling source file ..\cc\modules\xfeatures2d\SURFDetector.cc)
c:\users\giorg\documents\development\my repositories\electron-opencv\v2\node_modules\opencv4nodejs\cc\modules\xfeatures2d\SURFDetector.h(2): f
atal error C1083: Cannot open include file: 'opencv2/xfeatures2d.hpp': No such file or directory (compiling source file ..\cc\modules\xfeature
s2d\SURFDetector.cc) [C:\Users\giorg\Documents\Development\My repositories\electron-opencv\v2\node_modules\opencv4nodejs\build\opencv4nodejs.v
cxproj]
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Users\giorg\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\build.js:262:23)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
gyp ERR! System Windows_NT 10.0.17134
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\giorg\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\giorg\Documents\Development\My repositories\electron-opencv\v2\node_modules\opencv4nodejs
gyp ERR! node -v v8.11.3
gyp ERR! node-gyp -v v3.7.0
gyp ERR! not ok
npm WARN karma-jasmine-html-reporter@1.1.0 requires a peer of jasmine@>=3 but none is installed. You must install peer dependencies yourself.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! opencv4nodejs@4.7.1 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the opencv4nodejs@4.7.1 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\giorg\AppData\Roaming\npm-cache\_logs\2018-07-21T20_13_10_481Z-debug.log
PS C:\Users\giorg\Documents\Development\My repositories\electron-opencv\v2>
```

**Comment by George35mk** [comment]
I have installed python2.7 but again is failing to install, I spend 20 hours to understand why is not working just for the record.

**Comment by justadudewhohacks** [comment]
I think the issue is related to the path to your working directory containing a whitespace at `my repositories`. Make sure to fix that first. There a quite some other people having this issue.

**Comment by George35mk** [comment]
Worked thanks

**Comment by SuperSoftDev** [comment]
then how can I fix that? I mean whitespace at my repositories.

**Comment by justadudewhohacks** [comment]
Rename the directory with the whitespace?
