### ISSUE TITLE
Getting an error as "TypeError: Cannot destructure property `assertMetaData` of 'undefined' or 'null' ".

### ISSUE THREAD

**Issue by QA2Dev** [justadudewhohacks/opencv4nodejs#432]
I'm getting below error when I ran the **text.test.js** test.

C:\Users\E004223\Documents\opencv4nodejs>node test\tests\modules\text\text.test.js

**_Console Log_**
C:\Users\E004223\Documents\opencv4nodejs\test\tests\modules\text\text.test.js:3
  assertMetaData,
  ^

TypeError: Cannot destructure property `assertMetaData` of 'undefined' or 'null'.
    at Object.<anonymous> (C:\Users\E004223\Documents\opencv4nodejs\test\tests\modules\text\text.test.js:5:12)
    at Module._compile (internal/modules/cjs/loader.js:678:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:689:10)
    at Module.load (internal/modules/cjs/loader.js:589:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:528:12)
    at Function.Module._load (internal/modules/cjs/loader.js:520:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:719:10)
    at startup (internal/bootstrap/node.js:228:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:575:3)

**Comment by justadudewhohacks** [comment]
What are you actually trying to achieve? Running the tests? Take a look at the script:
`"test": "mocha --require ./globals --timeout 2000 --recursive ./tests"`

You have to require globals.js to run the tests.
