### ISSUE TITLE
OpenCV Error when try to run Example Code 

### ISSUE THREAD

**Issue by umaams** [justadudewhohacks/opencv4nodejs#438]
I try to run code in examples/faceDetect/webcamFaceDetectionGpu.js and I find error like this:

`terminate called after throwing an instance of 'std::runtime_error'
  what():  OpenCV Error: (The function is not implemented. Rebuild the library with Windows, GTK+ 2.x or Carbon support. If you are on Ubuntu or Debian, install libgtk2.0-dev and pkg-config, then re-run cmake or configure script) in cvShowImage, in file /media/umam/Programming/Projects/NodeJS/opencv4nodejs/node_modules/opencv-build/opencv/opencv/modules/highgui/src/window.cpp, line 632, status -2
[1]    15359 abort (core dumped)  node webcamFaceDetectionGpu.js
`

How to resolve this issue? thanks

**Comment by justadudewhohacks** [comment]
The error message tells you what to do. Install libgtk and recompile the package.

**Comment by SanyapongYoukachen** [comment]
I also have this issue in different error.

**sanyapong@sanyapong:~/Documents/opencv4nodejs-master/examples/faceDetect$ node faceDetection.js 
internal/modules/cjs/loader.js:683
  return process.dlopen(module, path.toNamespacedPath(filename));
                 ^
Error: /home/sanyapong/anaconda3/bin/../lib/libstdc++.so.6: version `GLIBCXX_3.4.22' not found (required by /home/sanyapong/Documents/opencv4nodejs-master/node_modules/opencv-build/opencv/build/lib/libopencv_objdetect.so.3.4)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:683:18)
    at Module.load (internal/modules/cjs/loader.js:566:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:506:12)
    at Function.Module._load (internal/modules/cjs/loader.js:498:3)
    at Module.require (internal/modules/cjs/loader.js:598:17)
    at require (internal/modules/cjs/helpers.js:11:18)
    at Object.<anonymous> (/home/sanyapong/Documents/opencv4nodejs-master/lib/cv.js:17:8)
    at Module._compile (internal/modules/cjs/loader.js:654:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:665:10)
    at Module.load (internal/modules/cjs/loader.js:566:32)**

How to resolve this issue? thank you very much.

**Comment by SanyapongYoukachen** [comment]
Ohh, it is the problem about my anaconda, so **conda install libgcc** can resolve it. thanks

**Comment by Simon1059770342** [comment]
> **conda install libgcc**

how do you solve it? Because I have much the same as you have.
  terminate called after throwing an instance of 'std::runtime_error'
  what():  OpenCV Error: (The function is not implemented. Rebuild the library with Windows, GTK+ 2.x or Carbon support. If you are on Ubuntu or Debian, install libgtk2.0-dev and pkg-config, then re-run cmake or configure script) in cvShowImage, in file /www/wwwroot/http/capture_back/node_modules/opencv-build/opencv/opencv/modules/highgui/src/window.cpp, line 632, status -2
Aborted
