### ISSUE TITLE
TypeScript Errors: tuple cannot be empty and Cannot find name Buffer during Transpile

### ISSUE THREAD

**Issue by bfox-fw** [justadudewhohacks/opencv4nodejs#453]
Thank you for your time.

I ran across a couple errors when transpiling Typescript in Angular 4

Environment is Windows and is built with Auto build  (  npm install --save opencv4nodejs )
Build output shows that the compiler is utilizing MSBuild V141 

Repro Steps: 
* In Angular 4, import the package ( import * as cv from 'opencv4nodejs' )
* Transpile the typescript and a stack-trace similar to the following should appear

************************************************************************************************************
```
[17:06:23]  typescript: K:/project-core/node_modules/opencv4nodejs/lib/typings/BFMatcher.d.ts, line: 9
            A tuple type element list cannot be empty.

       L8:  matchAsync(descriptors1: Mat, descriptors2: Mat): Promise<DescriptorMatch[]>;
       L9:  knnMatch(descriptors1: Mat, descriptors2: Mat, k: number): Array<[DescriptorMatch]|[]>;
      L10:  knnMatchAsync(descriptors1: Mat, descriptors2: Mat, k: number): Promise<Array<[DescriptorMatch]|[]>>;

[17:06:23]  typescript: K:/project-core/node_modules/opencv4nodejs/lib/typings/BFMatcher.d.ts, line: 10
            A tuple type element list cannot be empty.

       L9:      knnMatch(descriptors1: Mat, descriptors2: Mat, k: number): Array<[DescriptorMatch]|[]>;
      L10:      knnMatchAsync(descriptors1: Mat, descriptors2: Mat, k: number): Promise<Array<[DescriptorMatch]|[]>>;

[17:06:23]  typescript: K:/project-core/node_modules/opencv4nodejs/lib/typings/Mat.d.ts, line: 35
            Cannot find name 'Buffer'.

      L34:  constructor(dataArray: number[][][], type: number);
      L35:  constructor(data: Buffer, rows: number, cols: number, type?: number);
      L36:  abs(): Mat;

[17:06:23]  typescript: K:/project-core/node_modules/opencv4nodejs/lib/typings/Mat.d.ts, line: 165
            Cannot find name 'Buffer'.

     L164:  gaussianBlurAsync(kSize: Size, sigmaX: number, sigmaY?: number, borderType?: number): Promise<Mat>;
     L165:  getData(): Buffer;
     L166:  getDataAsync(): Promise<Buffer>;

[17:06:23]  typescript: K:/project-core/node_modules/opencv4nodejs/lib/typings/Mat.d.ts, line: 166
            Cannot find name 'Buffer'.

     L165:  getData(): Buffer;
     L166:  getDataAsync(): Promise<Buffer>;
     L167:  getDataAsArray(): number[][];

[17:06:23]  typescript: K:/project-core/node_modules/opencv4nodejs/lib/typings/cv.d.ts, line: 70
            Cannot find name 'Buffer'.

      L69:  export function getValidDisparityROIAsync(roi1: Rect[], roi2: Rect[], minDisparity: number, numberOfDisparities: number, SADWindowSize: number): Promise<Rect>;
      L70:  export function imdecode(buffer: Buffer, flags?: number): Mat;
      L71:  export function imdecodeAsync(buffer: Buffer, flags?: number): Promise<Mat>;

[17:06:23]  typescript: K:/project-core/node_modules/opencv4nodejs/lib/typings/cv.d.ts, line: 71
            Cannot find name 'Buffer'.

      L70:  export function imdecode(buffer: Buffer, flags?: number): Mat;
      L71:  export function imdecodeAsync(buffer: Buffer, flags?: number): Promise<Mat>;
      L72:  export function imencode(fileExt: string, img: Mat, flags?: number[]): Buffer;

[17:06:23]  typescript: K:/project-core/node_modules/opencv4nodejs/lib/typings/cv.d.ts, line: 72
            Cannot find name 'Buffer'.

      L71:  export function imdecodeAsync(buffer: Buffer, flags?: number): Promise<Mat>;
      L72:  export function imencode(fileExt: string, img: Mat, flags?: number[]): Buffer;
      L73:  export function imencodeAsync(fileExt: string, img: Mat, flags?: number[]): Promise<Buffer>;

[17:06:23]  typescript: K:/project-core/node_modules/opencv4nodejs/lib/typings/cv.d.ts, line: 73
            Cannot find name 'Buffer'.

      L72:  export function imencode(fileExt: string, img: Mat, flags?: number[]): Buffer;
      L73:  export function imencodeAsync(fileExt: string, img: Mat, flags?: number[]): Promise<Buffer>;
      L74:  export function imread(filePath: string, flags?: number): Mat;

[17:06:23]  ionic-app-script task: "build"
[17:06:23]  Error: Failed to transpile program
Error: Failed to transpile program
    at new BuildError (K:\project-core\node_modules\@ionic\app-scripts\dist\util\errors.js:16:28)
    at K:\project-core\node_modules\@ionic\app-scripts\dist\transpile.js:159:20
    at new Promise (<anonymous>)
    at transpileWorker (K:\project-core\node_modules\@ionic\app-scripts\dist\transpile.js:107:12)
    at Object.transpile (K:\project-core\node_modules\@ionic\app-scripts\dist\transpile.js:64:12)
    at K:\project-core\node_modules\@ionic\app-scripts\dist\build.js:109:82
    at <anonymous>
```
************************************************************************************************************

Note: I also tested the built opencv package in raw javascript in NodeJS and in the latest Electron via electron_rebuild and everything is working perfectly. The issue only appears when using Typescript.

**Comment by justadudewhohacks** [comment]
What's your typescript version? Also try to install @types/node.

**Comment by bfox-fw** [comment]
Thanks for your reply.

The typescript version installed is 2.6.2

Looks like @types/node is already installed and its version is 10.12.3

**Comment by justadudewhohacks** [comment]
So if @types/node is installed, Buffer should be defined. `A tuple type element list cannot be empty` can be fixed by upgrading your typescript version or maybe there is an option you can set in your tsconfig, to relax this check, but I am not sure.

**Comment by justadudewhohacks** [comment]
Closing, if this is still an issue, feel free to reopen.
