### ISSUE TITLE
build error: use of undeclared identifier 'String' 

### ISSUE THREAD

**Issue by bookjan** [justadudewhohacks/opencv4nodejs#468]
Hi guys, 

I want to bind "cv::dnn::Net::getLayerNames" for Net. But I got an error:

```
opencv4nodejs git:(master) ✗ npm run build

> opencv4nodejs@4.10.1 build /Users/jansu/Development/contribution/opencv4nodejs
> node-gyp configure build

  CXX(target) Release/obj.target/opencv4nodejs/cc/modules/dnn/Net.o
In file included from ../cc/modules/dnn/Net.cc:9:
../cc/modules/dnn/NetBindings.h:97:35: error: use of undeclared identifier 'String'
      return ObjectArrayConverter<String, cv::String>::wrap(returnValue);
                                  ^
In file included from ../cc/modules/dnn/Net.cc:1:
In file included from /usr/local/include/opencv2/core.hpp:52:
In file included from /usr/local/include/opencv2/core/cvdef.h:474:
In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/array:109:
In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/algorithm:643:
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/memory:3656:5: warning: destructor called on non-final 'NetBindings::SetInputWorker' that has virtual functions but non-virtual destructor [-Wdelete-non-virtual-dtor]
    __data_.second().~_Tp();
    ^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/memory:3617:9: note: in instantiation of member function 'std::__1::__shared_ptr_emplace<NetBindings::SetInputWorker, std::__1::allocator<NetBindings::SetInputWorker> >::__on_zero_shared'
      requested here
        __shared_ptr_emplace(_Alloc __a, _Args&& ...__args)
        ^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/memory:4277:26: note: in instantiation of function template specialization 'std::__1::__shared_ptr_emplace<NetBindings::SetInputWorker, std::__1::allocator<NetBindings::SetInputWorker>
      >::__shared_ptr_emplace<cv::dnn::experimental_dnn_34_v7::Net>' requested here
    ::new(__hold2.get()) _CntrlBlk(__a2, _VSTD::forward<_Args>(__args)...);
                         ^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/memory:4656:29: note: in instantiation of function template specialization 'std::__1::shared_ptr<NetBindings::SetInputWorker>::make_shared<cv::dnn::experimental_dnn_34_v7::Net>' requested
      here
    return shared_ptr<_Tp>::make_shared(_VSTD::forward<_Args>(__args)...);
                            ^
../cc/modules/dnn/Net.cc:37:10: note: in instantiation of function template specialization 'std::__1::make_shared<NetBindings::SetInputWorker, cv::dnn::experimental_dnn_34_v7::Net>' requested here
    std::make_shared<NetBindings::SetInputWorker>(Net::Converter::unwrap(info.This())),
         ^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/memory:3656:23: note: qualify call to silence this warning
    __data_.second().~_Tp();
                      ^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/memory:3656:5: warning: destructor called on non-final 'NetBindings::ForwardWorker' that has virtual functions but non-virtual destructor [-Wdelete-non-virtual-dtor]
    __data_.second().~_Tp();
    ^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/memory:3617:9: note: in instantiation of member function 'std::__1::__shared_ptr_emplace<NetBindings::ForwardWorker, std::__1::allocator<NetBindings::ForwardWorker> >::__on_zero_shared'
      requested here
        __shared_ptr_emplace(_Alloc __a, _Args&& ...__args)
        ^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/memory:4277:26: note: in instantiation of function template specialization 'std::__1::__shared_ptr_emplace<NetBindings::ForwardWorker, std::__1::allocator<NetBindings::ForwardWorker>
      >::__shared_ptr_emplace<cv::dnn::experimental_dnn_34_v7::Net>' requested here
    ::new(__hold2.get()) _CntrlBlk(__a2, _VSTD::forward<_Args>(__args)...);
                         ^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/memory:4656:29: note: in instantiation of function template specialization 'std::__1::shared_ptr<NetBindings::ForwardWorker>::make_shared<cv::dnn::experimental_dnn_34_v7::Net>' requested here
    return shared_ptr<_Tp>::make_shared(_VSTD::forward<_Args>(__args)...);
                            ^
../cc/modules/dnn/Net.cc:53:10: note: in instantiation of function template specialization 'std::__1::make_shared<NetBindings::ForwardWorker, cv::dnn::experimental_dnn_34_v7::Net>' requested here
    std::make_shared<NetBindings::ForwardWorker>(Net::Converter::unwrap(info.This())),
         ^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/memory:3656:23: note: qualify call to silence this warning
    __data_.second().~_Tp();
                      ^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/memory:3656:5: warning: destructor called on non-final 'NetBindings::GetLayerNamesWorker' that has virtual functions but non-virtual destructor [-Wdelete-non-virtual-dtor]
    __data_.second().~_Tp();
    ^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/memory:3617:9: note: in instantiation of member function 'std::__1::__shared_ptr_emplace<NetBindings::GetLayerNamesWorker, std::__1::allocator<NetBindings::GetLayerNamesWorker>
      >::__on_zero_shared' requested here
        __shared_ptr_emplace(_Alloc __a, _Args&& ...__args)
        ^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/memory:4277:26: note: in instantiation of function template specialization 'std::__1::__shared_ptr_emplace<NetBindings::GetLayerNamesWorker,
      std::__1::allocator<NetBindings::GetLayerNamesWorker> >::__shared_ptr_emplace<cv::dnn::experimental_dnn_34_v7::Net>' requested here
    ::new(__hold2.get()) _CntrlBlk(__a2, _VSTD::forward<_Args>(__args)...);
                         ^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/memory:4656:29: note: in instantiation of function template specialization 'std::__1::shared_ptr<NetBindings::GetLayerNamesWorker>::make_shared<cv::dnn::experimental_dnn_34_v7::Net>'
      requested here
    return shared_ptr<_Tp>::make_shared(_VSTD::forward<_Args>(__args)...);
                            ^
../cc/modules/dnn/Net.cc:69:12: note: in instantiation of function template specialization 'std::__1::make_shared<NetBindings::GetLayerNamesWorker, cv::dnn::experimental_dnn_34_v7::Net>' requested here
      std::make_shared<NetBindings::GetLayerNamesWorker>(Net::Converter::unwrap(info.This())),
           ^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/memory:3656:23: note: qualify call to silence this warning
    __data_.second().~_Tp();
                      ^
3 warnings and 1 error generated.
make: *** [Release/obj.target/opencv4nodejs/cc/modules/dnn/Net.o] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/jansu/.nvm/versions/node/v8.11.2/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
gyp ERR! System Darwin 18.2.0
gyp ERR! command "/Users/jansu/.nvm/versions/node/v8.11.2/bin/node" "/Users/jansu/.nvm/versions/node/v8.11.2/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "build"
gyp ERR! cwd /Users/jansu/Development/contribution/opencv4nodejs
gyp ERR! node -v v8.11.2
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! opencv4nodejs@4.10.1 build: `node-gyp configure build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the opencv4nodejs@4.10.1 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/jansu/.npm/_logs/2018-12-04T10_32_18_004Z-debug.log
```

Here code snippet in my NetBindings.h:
```
  struct GetLayerNamesWorker : public CatchCvExceptionWorker {
  public:
    cv::dnn::Net self;
    GetLayerNamesWorker(cv::dnn::Net self) {
      this->self = self;
    }

    std::vector<cv::String> returnValue;

    std::string executeCatchCvExceptionWorker() {
      returnValue = self.getLayerNames();
      return "";
    }

    v8::Local<v8::Value> getReturnValue(){
      return ObjectArrayConverter<String, cv::String>::wrap(returnValue);
    }
  };
```
Does anynoe know what's going on? 

Any help would be appreciated.

**Comment by bookjan** [comment]
After modifying my code to this:
```
  struct GetLayerNamesWorker : public CatchCvExceptionWorker {
  public:
    cv::dnn::Net self;
    GetLayerNamesWorker(cv::dnn::Net self) {
      this->self = self;
    }

    std::vector<cv::String> layerNames;

    std::string executeCatchCvExceptionWorker() {
      layerNames = self.getLayerNames();
      return "";
    }

    v8::Local<v8::Value> getReturnValue() {
      v8::Local<v8::Array> jsArr = Nan::New<v8::Array>(layerNames.size());
      for (int i = 0; i < jsArr->Length(); i++) {
        std::string name = layerNames.at(i);
        jsArr->Set(i, StringConverter::wrap(name));
      }
      return jsArr;
    }
  };
```

The bindings is working properly.

**Comment by justadudewhohacks** [comment]
Uhm did you try StringArrayConverter::wrap(returnValue)?

**Comment by bookjan** [comment]
After I tried  "StringArrayConverter::wrap()" the build got the other error.

Here is full log for build:

```
➜  opencv4nodejs git:(master) ✗ npm run build

> opencv4nodejs@4.11.0 build /Users/jansu/Development/contribution/opencv4nodejs
> node-gyp configure build

  CXX(target) Release/obj.target/opencv4nodejs/cc/modules/dnn/Net.o
In file included from ../cc/modules/dnn/Net.cc:9:
../cc/modules/dnn/NetBindings.h:97:41: error: no viable conversion from 'vector<cv::String, allocator<cv::String>>' to
      'vector<std::__1::basic_string<char>, allocator<std::__1::basic_string<char>>>'
      return StringArrayConverter::wrap(layerNames);
                                        ^~~~~~~~~~
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/vector:534:5: note: candidate constructor not viable: no
      known conversion from 'std::vector<cv::String>' to 'const std::__1::vector<std::__1::basic_string<char>,
      std::__1::allocator<std::__1::basic_string<char> > > &' for 1st argument
    vector(const vector& __x);
    ^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/vector:541:5: note: candidate constructor not viable: no
      known conversion from 'std::vector<cv::String>' to 'initializer_list<std::__1::vector<std::__1::basic_string<char>,
      std::__1::allocator<std::__1::basic_string<char> > >::value_type>' (aka 'initializer_list<std::__1::basic_string<char> >') for 1st argument
    vector(initializer_list<value_type> __il);
    ^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/vector:547:5: note: candidate constructor not viable: no
      known conversion from 'std::vector<cv::String>' to 'std::__1::vector<std::__1::basic_string<char>, std::__1::allocator<std::__1::basic_string<char> > >
      &&' for 1st argument
    vector(vector&& __x)
    ^
/Users/jansu/Development/contribution/opencv4nodejs/node_modules/native-node-utils/src/AbstractConverter.h:59:37: note: passing argument to parameter 'val'
      here
        static v8::Local<v8::Value> wrap(T val) {
                                           ^
In file included from ../cc/modules/dnn/Net.cc:1:
In file included from /usr/local/include/opencv2/core.hpp:52:
In file included from /usr/local/include/opencv2/core/cvdef.h:474:
In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/array:109:
In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/algorithm:643:
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/memory:3656:5: warning: destructor called on non-final
      'NetBindings::SetInputWorker' that has virtual functions but non-virtual destructor [-Wdelete-non-virtual-dtor]
    __data_.second().~_Tp();
    ^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/memory:3617:9: note: in instantiation of member function
      'std::__1::__shared_ptr_emplace<NetBindings::SetInputWorker, std::__1::allocator<NetBindings::SetInputWorker> >::__on_zero_shared' requested here
        __shared_ptr_emplace(_Alloc __a, _Args&& ...__args)
        ^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/memory:4277:26: note: in instantiation of function template
      specialization 'std::__1::__shared_ptr_emplace<NetBindings::SetInputWorker, std::__1::allocator<NetBindings::SetInputWorker>
      >::__shared_ptr_emplace<cv::dnn::experimental_dnn_34_v7::Net>' requested here
    ::new(__hold2.get()) _CntrlBlk(__a2, _VSTD::forward<_Args>(__args)...);
                         ^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/memory:4656:29: note: in instantiation of function template
      specialization 'std::__1::shared_ptr<NetBindings::SetInputWorker>::make_shared<cv::dnn::experimental_dnn_34_v7::Net>' requested here
    return shared_ptr<_Tp>::make_shared(_VSTD::forward<_Args>(__args)...);
                            ^
../cc/modules/dnn/Net.cc:38:10: note: in instantiation of function template specialization 'std::__1::make_shared<NetBindings::SetInputWorker,
      cv::dnn::experimental_dnn_34_v7::Net>' requested here
    std::make_shared<NetBindings::SetInputWorker>(Net::Converter::unwrap(info.This())),
         ^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/memory:3656:23: note: qualify call to silence this warning
    __data_.second().~_Tp();
                      ^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/memory:3656:5: warning: destructor called on non-final
      'NetBindings::ForwardWorker' that has virtual functions but non-virtual destructor [-Wdelete-non-virtual-dtor]
    __data_.second().~_Tp();
    ^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/memory:3617:9: note: in instantiation of member function
      'std::__1::__shared_ptr_emplace<NetBindings::ForwardWorker, std::__1::allocator<NetBindings::ForwardWorker> >::__on_zero_shared' requested here
        __shared_ptr_emplace(_Alloc __a, _Args&& ...__args)
        ^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/memory:4277:26: note: in instantiation of function template
      specialization 'std::__1::__shared_ptr_emplace<NetBindings::ForwardWorker, std::__1::allocator<NetBindings::ForwardWorker>
      >::__shared_ptr_emplace<cv::dnn::experimental_dnn_34_v7::Net>' requested here
    ::new(__hold2.get()) _CntrlBlk(__a2, _VSTD::forward<_Args>(__args)...);
                         ^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/memory:4656:29: note: in instantiation of function template
      specialization 'std::__1::shared_ptr<NetBindings::ForwardWorker>::make_shared<cv::dnn::experimental_dnn_34_v7::Net>' requested here
    return shared_ptr<_Tp>::make_shared(_VSTD::forward<_Args>(__args)...);
                            ^
../cc/modules/dnn/Net.cc:54:10: note: in instantiation of function template specialization 'std::__1::make_shared<NetBindings::ForwardWorker,
      cv::dnn::experimental_dnn_34_v7::Net>' requested here
    std::make_shared<NetBindings::ForwardWorker>(Net::Converter::unwrap(info.This())),
         ^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/memory:3656:23: note: qualify call to silence this warning
    __data_.second().~_Tp();
                      ^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/memory:3656:5: warning: destructor called on non-final
      'NetBindings::GetLayerNamesWorker' that has virtual functions but non-virtual destructor [-Wdelete-non-virtual-dtor]
    __data_.second().~_Tp();
    ^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/memory:3617:9: note: in instantiation of member function
      'std::__1::__shared_ptr_emplace<NetBindings::GetLayerNamesWorker, std::__1::allocator<NetBindings::GetLayerNamesWorker> >::__on_zero_shared' requested
      here
        __shared_ptr_emplace(_Alloc __a, _Args&& ...__args)
        ^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/memory:4277:26: note: in instantiation of function template
      specialization 'std::__1::__shared_ptr_emplace<NetBindings::GetLayerNamesWorker, std::__1::allocator<NetBindings::GetLayerNamesWorker>
      >::__shared_ptr_emplace<cv::dnn::experimental_dnn_34_v7::Net>' requested here
    ::new(__hold2.get()) _CntrlBlk(__a2, _VSTD::forward<_Args>(__args)...);
                         ^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/memory:4656:29: note: in instantiation of function template
      specialization 'std::__1::shared_ptr<NetBindings::GetLayerNamesWorker>::make_shared<cv::dnn::experimental_dnn_34_v7::Net>' requested here
    return shared_ptr<_Tp>::make_shared(_VSTD::forward<_Args>(__args)...);
                            ^
../cc/modules/dnn/Net.cc:70:12: note: in instantiation of function template specialization 'std::__1::make_shared<NetBindings::GetLayerNamesWorker,
      cv::dnn::experimental_dnn_34_v7::Net>' requested here
      std::make_shared<NetBindings::GetLayerNamesWorker>(Net::Converter::unwrap(info.This())),
           ^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/memory:3656:23: note: qualify call to silence this warning
    __data_.second().~_Tp();
                      ^
3 warnings and 1 error generated.
make: *** [Release/obj.target/opencv4nodejs/cc/modules/dnn/Net.o] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/jansu/.nvm/versions/node/v8.11.2/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
gyp ERR! System Darwin 18.2.0
gyp ERR! command "/Users/jansu/.nvm/versions/node/v8.11.2/bin/node" "/Users/jansu/.nvm/versions/node/v8.11.2/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "build"
gyp ERR! cwd /Users/jansu/Development/contribution/opencv4nodejs
gyp ERR! node -v v8.11.2
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! opencv4nodejs@4.11.0 build: `node-gyp configure build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the opencv4nodejs@4.11.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/jansu/.npm/_logs/2018-12-06T22_51_01_184Z-debug.log
```
Here is my code snapshot with line number:
![screen shot 2018-12-07 at 6 39 31 am](https://user-images.githubusercontent.com/1734406/49616518-18e41900-f9ec-11e8-91bc-1b873480beae.png)

**Comment by justadudewhohacks** [comment]
I think the issue is, that you have an std::vector<cv::string>, but StringArrayConverter works on std::vector<std::string>. [Here](https://github.com/justadudewhohacks/opencv4nodejs/blob/ff3ce09820e1e7cc792efe794f7e90c6201a6465/cc/modules/dnn/NetBindings.h#L55) is an example of how StringArrayConverter is used to wrap the output blob names.

Can you not simply declare layerNames as std::vector<std::string>? If that doesn't work, you would probably have to iterate over the vector once and cast the elements from cv::String to std::string.

**Comment by justadudewhohacks** [comment]
Sure! Do not hesitate to submit any kind of PRs please :)
