### ISSUE TITLE
Can not install opencv4nodejs 

### ISSUE THREAD

**Issue by nguyenndvn** [justadudewhohacks/opencv4nodejs#477]
Dear Author,
I can not install opencv4nodejs.
Steps, I did:
1) npm install windows-build-tools --vs2015
-> Successfully [OK]
2) npm i opencv4nodejs
ERR:
the log:
XXXXXXXXXXX\node_modules\opencv4nodejs>if not defined npm_config_no
de_gyp (node "C:\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin
\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "C:\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild )
The system cannot find the path specified.
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (C:\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:345:16)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_proces
s.js:240:12)
gyp ERR! System Windows_NT 6.1.7600
gyp ERR! command "C:\\nodejs\\node.exe" "C:\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd xxxxxxxxxxxxxxxxxx\node_modules\opencv4nodejs
gyp ERR! node -v v10.14.2
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! opencv4nodejs@4.13.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the opencv4nodejs@4.13.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional log
ging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\my_pc\AppData\Roaming\npm-cache\_logs\2018-12-22T10_02_23_
542Z-debug.log

**Comment by manishboricha** [comment]
I am getting same error and i have made node and npm version bold inside the error please check : 

I am trying to installing this on MacOS Mojave 10.14.3

Getting below error at the end of the installation :

793 timing stage:rollbackFailedOptional Completed in 3425ms
794 timing stage:runTopLevelLifecycles Completed in 1078945ms
795 verbose stack Error: opencv-build@0.0.17 install: node ./install.js
795 verbose stack Exit status 1
795 verbose stack at EventEmitter. (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:301:16)
795 verbose stack at EventEmitter.emit (events.js:197:13)
795 verbose stack at ChildProcess. (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
795 verbose stack at ChildProcess.emit (events.js:197:13)
795 verbose stack at maybeClose (internal/child_process.js:978:16)
795 verbose stack at Process.ChildProcess._handle.onexit (internal/child_process.js:265:5)
796 verbose pkgid opencv-build@0.0.17
797 verbose cwd /Users/manishboricha/eclipse-workspace/Kings_iOS
798 verbose Darwin 18.2.0
799 verbose argv "/usr/local/Cellar/node/11.9.0/bin/node" "/usr/local/bin/npm" "i" "-g" "opencv4nodejs"
**800 verbose node v11.9.0
801 verbose npm v6.5.0**
802 error code ELIFECYCLE
803 error errno 1
804 error opencv-build@0.0.17 install: node ./install.js
804 error Exit status 1
805 error Failed at the opencv-build@0.0.17 install script.
805 error This is probably not a problem with npm. There is likely additional logging output above.
806 verbose exit [ 1, true ]

**Comment by Reddyforcode** [comment]
did you get a solution?
