### ISSUE TITLE
Error: The specified module could not be found. [Windows 7 64bit]

### ISSUE THREAD

**Issue by J-DreaMy** [justadudewhohacks/opencv4nodejs#497]
`internal/modules/cjs/loader.js:718
  return process.dlopen(module, path.toNamespacedPath(filename));
                 ^

Error: The specified module could not be found.
\\?\C:\Users\suryansh\Desktop\d\node-opencv-test\node_modules\opencv4nodejs\build\Release\opencv4nodejs.node
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:718:18)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (C:\Users\suryansh\Desktop\d\node-opencv-test\node_modules\opencv4nodejs\lib\cv.js:17:8)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)`

i already tried see #388, #106, #50 to fixed the error. 

echo %OPENCV4NODEJS_DISABLE_AUTOBUILD%
1

echo %OPENCV_LIB_DIR%
C:\opencv\build\x64\vc14\lib

echo %OPENCV_INCLUDE_DIR%
C:\opencv\build\include

echo %OPENCV_DIR%
C:\opencv\build\x64\vc14

echo %C:\opencv\build\x64\vc15\bin%
%C:\opencv\build\x64\vc15\bin%

echo %path%
C:\Users\User\AppData\Local\Yarn\config\global\node_modules\.bin;C:\Users\User\AppData\Roaming\npm;C:\Users\User\AppData\Roaming\Composer\vendor\bin;;C:\laragon\bin\laragon\utils;C:\laragon\bin\mysql\mysql-5.7.19-winx64\bin;C:\laragon\bin\php\php-7.1.7-Win32-VC14-x64;C:\laragon\bin\composer;C:\laragon\bin\apache\httpd-2.4.27-win64-VC14\bin;C:\laragon\bin\redis\redis-x64-3.2.100;C:\laragon\bin\nodejs\node-v10.15.0-x64;C:\laragon\bin\yarn\bin;C:\laragon\bin\nginx\nginx-1.12.0;C:\laragon\bin\notepad++;C:\laragon\bin\telnet;C:\laragon\bin\ngrok;C:\laragon\bin\git\bin;C:\laragon\bin\git\cmd;C:\laragon\bin\git\usr\bin;C:\laragon\bin\git\mingw64\bin;C:\laragon\bin;C:\laragon\usr\bin;C:\laragon\bin\putty;C:\laragon\bin\cmder\bin;C:\laragon\bin\cmder\vendor\conemu-maximus5\ConEmu\Scripts;C:\laragon\bin\cmder\vendor\conemu-maximus5;C:\laragon\bin\cmder\vendor\conemu-maximus5\ConEmu;C:\Program Files (x86)\AMD APP\bin\x86_64;C:\Program Files (x86)\AMD APP\bin\x86;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\ATI Technologies\ATI.ACE\Core-Static;C:\laragon\bin\php\php-7.1.7-Win32-VC14-x64;C:\ProgramData\ComposerSetup\bin;C:\Program Files\Git\cmd;C:\Program Files\CMake\bin;C:\Program Files\nodejs;C:\opencv\build\x64\vc15\bin\;C:\laragon\bin;C:\laragon\bin\apache\httpd-2.4.27-win64-VC14\bin;C:\laragon\bin\composer;C:\laragon\bin\git\bin;C:\laragon\bin\git\cmd;C:\laragon\bin\git\mingw64\bin;C:\laragon\bin\git\usr\bin;C:\laragon\bin\laragon\utils;C:\laragon\bin\mysql\mysql-5.7.19-winx64\bin;C:\laragon\bin\nginx\nginx-1.12.0;C:\laragon\bin\ngrok;C:\laragon\bin\nodejs\node-v10.15.0-x64;C:\laragon\bin\notepad++;C:\laragon\bin\php\php-7.1.7-Win32-VC14-x64;C:\laragon\bin\putty;C:\laragon\bin\redis\redis-x64-3.2.100;C:\laragon\bin\telnet;C:\laragon\bin\yarn\bin;C:\laragon\usr\bin;C:\Users\User\AppData\Local\Yarn\config\global\node_modules\.bin;C:\Users\User\AppData\Roaming\Composer\vendor\bin;C:\Users\User\AppData\Roaming\npm;C:\Users\User\.windows-build-tools\python27\;C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin;C:\Users\User\AppData\Roaming\npm\node_modules\windows-build-tools\node_modules\.bin;C:\Program Files\Git\mingw64\bin;C:\Program Files\Git\usr\bin;C:\Program Files (x86)\AMD APP\bin\x86_64;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0;C:\Program Files (x86)\ATI Technologies\ATI.ACE\Core-Static;C:\ProgramData\ComposerSetup\bin;C:\Program Files\Git\cmd;C:\Program Files\nodejs;C:\Users\User\AppData\Local\atom\bin;C:\Users\User\AppData\Local\Programs\Microsoft VS Code\bin;**C:\opencv\build\x64\vc14\bin**;C:\Program Files\Git\usr\bin;C:\Program Files\Git\usr\share\vim\vim74;C:\laragon\bin\cmder\;

use opencv-3.4.4-vc14_vc15
hope someone will help me, thanks for reply

**Comment by pboymt** [comment]
same problem

**Comment by giegiey** [comment]
reinstall nodejs
npm install --global windows-build-tools --vs2015
npm install opencv4nodejs

**Comment by sajithgr** [comment]
hai guys ,

please suggest any workaround for this issue:

[debug] �[35m[Support]�[39m \?\C:\Users\******\AppData\Roaming\npm\node_modules\opencv4nodejs\build\Release\opencv4nodejs.node
[debug] �[35m[Support]�[39m Failed to load global package 'opencv4nodejs': The "path" argument must be of type string. Received type undefined

opencvnode4js installaion was suceess with no issues, but appium cant load the module
windows 10
appium 1.18.0
opencv4nodejs@5.6.0
