### ISSUE TITLE
can't install new version

### ISSUE THREAD

**Issue by VeeDock** [justadudewhohacks/opencv4nodejs#585]
hi! i cant install new version opencv4nodejs.
i always got this error: 

```
[ 87%] Building CXX object modules/xfeatures2d/CMakeFiles/opencv_xfeatures2d.dir/src/boostdesc.cpp.o
/home/bigeye/node/ase/node_modules/opencv-build/opencv/opencv_contrib/modules/xfeatures2d/src/boostdesc.cpp:653:37: fatal error: boostdesc_bgm.i: No such file or directory
           #include "boostdesc_bgm.i"
                                     ^
compilation terminated.
make[2]: *** [modules/xfeatures2d/CMakeFiles/opencv_xfeatures2d.dir/src/boostdesc.cpp.o] Error 1
make[1]: *** [modules/xfeatures2d/CMakeFiles/opencv_xfeatures2d.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[ 87%] Building CXX object modules/ximgproc/CMakeFiles/opencv_ximgproc.dir/src/anisodiff.cpp.o
[ 88%] Building CXX object modules/ximgproc/CMakeFiles/opencv_ximgproc.dir/src/bilateral_texture

....

[ 91%] Building CXX object modules/ximgproc/CMakeFiles/opencv_ximgproc.dir/src/thinning.cpp.o
[ 91%] Building CXX object modules/ximgproc/CMakeFiles/opencv_ximgproc.dir/src/weighted_median_filter.cpp.o
[ 91%] Building CXX object modules/ximgproc/CMakeFiles/opencv_ximgproc.dir/opencl_kernels_ximgproc.cpp.o
[ 91%] Linking CXX shared library ../../lib/libopencv_ximgproc.so
[ 91%] Built target opencv_ximgproc
make: *** [all] Error 2
ERR! child process exited with code 2 (for more info, set '--loglevel silly') 
npm WARN asedesktop@0.1.0 No description
npm WARN asedesktop@0.1.0 No repository field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! opencv-build@0.1.4 install: `node ./install.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the opencv-build@0.1.4 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/bigeye/.npm/_logs/2019-06-25T20_59_41_633Z-debug.log

```

may be you can help me with it? 
thanks

**Comment by VeeDock** [comment]
on other computer with centos too i got other error: 

....
```
   CXX(target) Release/obj.target/opencv4nodejs/cc/io/VideoCapture.o
  CXX(target) Release/obj.target/opencv4nodejs/cc/io/VideoWriter.o
  CXX(target) Release/obj.target/opencv4nodejs/cc/photo/photo.o
  CXX(target) Release/obj.target/opencv4nodejs/cc/photo/photoConstants.o
  CXX(target) Release/obj.target/opencv4nodejs/cc/video/video.o
  CXX(target) Release/obj.target/opencv4nodejs/cc/video/BackgroundSubtractor.o
  CXX(target) Release/obj.target/opencv4nodejs/cc/video/BackgroundSubtractorMOG2.o
  CXX(target) Release/obj.target/opencv4nodejs/cc/video/BackgroundSubtractorKNN.o
  CXX(target) Release/obj.target/opencv4nodejs/cc/ximgproc/ximgproc.o
  CXX(target) Release/obj.target/opencv4nodejs/cc/ximgproc/MatXimgproc.o
  CXX(target) Release/obj.target/opencv4nodejs/cc/ximgproc/SuperpixelSEEDS.o
  CXX(target) Release/obj.target/opencv4nodejs/cc/ximgproc/SuperpixelSLIC.o
  CXX(target) Release/obj.target/opencv4nodejs/cc/ximgproc/SuperpixelLSC.o
  CXX(target) Release/obj.target/opencv4nodejs/cc/objdetect/objdetect.o
  CXX(target) Release/obj.target/opencv4nodejs/cc/objdetect/CascadeClassifier.o
In file included from /home/vasia/node/opencvtest/node_modules/native-node-utils/src/NativeNodeUtils.h:10:0,
                 from ../cc/macros.h:1,
                 from ../cc/opencv_modules.h:1,
                 from ../cc/objdetect/objdetect.cc:1:
/home/vasia/node/opencvtest/node_modules/native-node-utils/src/ObjectWrap.h: In constructor ‘FF::ObjectWrapTemplate<HOGDescriptor, std::shared_ptr<cv::HOGDescriptor> >::ConstructorBase::ConstructorBase()’:
/home/vasia/node/opencvtest/node_modules/native-node-utils/src/ObjectWrap.h:130:9: error: conversion from ‘FF::ObjectWrapTemplate<HOGDescriptor, std::shared_ptr<cv::HOGDescriptor> >::ConstructorBase::__lambda0’ to non-scalar type ‘std::function<void(HOGDescriptor*)>’ requested
   class ConstructorBase : public BindingBase, public ISyncWorker {
         ^
In file included from ../cc/objdetect/objdetect.cc:7:0:
../cc/objdetect/HOGDescriptor.h: In constructor ‘HOGDescriptor::Constructor::Constructor(Nan::NAN_METHOD_ARGS_TYPE)’:
../cc/objdetect/HOGDescriptor.h:85:47: note: synthesized method ‘FF::ObjectWrapTemplate<HOGDescriptor, std::shared_ptr<cv::HOGDescriptor> >::ConstructorBase::ConstructorBase()’ first required here
   Constructor(Nan::NAN_METHOD_ARGS_TYPE info) {
                                               ^
make: *** [Release/obj.target/opencv4nodejs/cc/objdetect/objdetect.o] Error 1
make: *** Waiting for unfinished jobs....
make: Leaving directory `/home/vasia/node/opencvtest/node_modules/opencv4nodejs/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:200:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)
gyp ERR! System Linux 3.10.0-957.21.3.el7.x86_64
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--jobs" "max"
gyp ERR! cwd /home/vasia/node/opencvtest/node_modules/opencv4nodejs
gyp ERR! node -v v12.4.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
npm WARN enoent ENOENT: no such file or directory, open '/home/vasia/node/opencvtest/package.json'
npm WARN opencvtest No description
npm WARN opencvtest No repository field.
npm WARN opencvtest No README data
npm WARN opencvtest No license field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! opencv4nodejs@5.0.0 install: `node-gyp rebuild --jobs max`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the opencv4nodejs@5.0.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/vasia/.npm/_logs/2019-06-26T02_49_15_662Z-debug.log
```

**Comment by justadudewhohacks** [comment]
For the first error see this [issue](https://github.com/opencv/opencv_contrib/issues/1301), downloading boostdesc_bgm.i might have failed during execution of the cmake script.

For the second issue I am not quite sure, what's your gcc/gxx version, are they c++ 11 compatible? Try upgrading your toolchain.

**Comment by VeeDock** [comment]
i have solved second issue. thank you. just upgrade my gcc with such commands:
```
sudo yum install centos-release-scl
sudo yum install devtoolset-7-gcc*
scl enable devtoolset-7 bash
```

**Comment by CharlieZheng** [comment]
How to fix the first error?
