### ISSUE TITLE
Error while install on CWP 7 (CentOS 7)

### ISSUE THREAD

**Issue by jamaglian** [justadudewhohacks/opencv4nodejs#588]
# Error Message

```
In file included from /root/node_modules/native-node-utils/src/NativeNodeUtils.h:10:0,
                 from ../cc/macros.h:1,
                 from ../cc/opencv_modules.h:1,
                 from ../cc/objdetect/objdetect.cc:1:
/root/node_modules/native-node-utils/src/ObjectWrap.h: In constructor ‘FF::ObjectWrapTemplate<HOGDescriptor, std::shared_ptr<cv::HOGDescriptor> >::ConstructorBase::ConstructorBase()’:
/root/node_modules/native-node-utils/src/ObjectWrap.h:130:9: error: conversion from ‘FF::ObjectWrapTemplate<HOGDescriptor, std::shared_ptr<cv::HOGDescriptor> >::ConstructorBase::__lambda0’ to non-scalar type ‘std::function<void(HOGDescriptor*)>’ requested
   class ConstructorBase : public BindingBase, public ISyncWorker {
         ^
In file included from ../cc/objdetect/objdetect.cc:7:0:
../cc/objdetect/HOGDescriptor.h: In constructor ‘HOGDescriptor::Constructor::Constructor(Nan::NAN_METHOD_ARGS_TYPE)’:
../cc/objdetect/HOGDescriptor.h:85:47: note: synthesized method ‘FF::ObjectWrapTemplate<HOGDescriptor, std::shared_ptr<cv::HOGDescriptor> >::ConstructorBase::ConstructorBase()’ first required here
   Constructor(Nan::NAN_METHOD_ARGS_TYPE info) {
                                               ^
make: *** [Release/obj.target/opencv4nodejs/cc/objdetect/objdetect.o] Error 1
make: Leaving directory `/root/node_modules/opencv4nodejs/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:198:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:248:12)
gyp ERR! System Linux 3.10.0-957.21.3.el7.x86_64
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--jobs" "max"
gyp ERR! cwd /root/node_modules/opencv4nodejs
gyp ERR! node -v v10.16.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
npm WARN enoent ENOENT: no such file or directory, open '/root/package.json'
npm WARN root No description
npm WARN root No repository field.
npm WARN root No README data
npm WARN root No license field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! opencv4nodejs@5.1.0 install: `node-gyp rebuild --jobs max`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the opencv4nodejs@5.1.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2019-07-03T16_11_27_673Z-debug.log

```

*OpenCV version* (example 3.4.1): ?.?.?

*With OpenCV-contrib?* (extra modules): yes/no?No

*OS*: Windows 7 / 8 / 10? / MacOSX? / Ubuntu? CentOS 7

*CentOS 7 using CWP*

I tried too many times but always with this, i need help please

**Comment by Simon1059770342** [comment]
Hi there, I just have much the same question as you have, so have you done it?

**Comment by jamaglian** [comment]
> Hi there, I just have much the same question as you have, so have you done it?

Sorry but I will not remember what I did complete but, you can't install opencv4nodejs with CWP, install the opencv4nodejs before the CWP, for the opencv4nodejs install thay dependencies:
```
sudo yum install epel-release git gcc gcc-c++ cmake3 qt5-qtbase-devel python python-devel python-pip cmake
sudo yum install python-devel numpy python34-numpy gtk2-devel libpng-devel jasper-devel openexr-devel libwebp-devel
sudo yum install libjpeg-turbo-devel libtiff-devel  libdc1394-devel tbb-devel eigen3-devel gstreamer-plugins-base-devel
sudo yum install freeglut-devel mesa-libGL mesa-libGL-devel  boost boost-thread boost-devel libv4l-devel
sudo yum install centos-release-scl
sudo yum install devtoolset-7-gcc*
scl enable devtoolset-7 bash
```
If i remember is that i maked, do not hesitate to ask again if that fail, or work to help.

**Comment by justadudewhohacks** [comment]
So I am assuming your issue is fixed? I am closing this, if it's not fixed feel free to reopen.
