### ISSUE TITLE
Error: module.js:681 

### ISSUE THREAD

**Issue by Simon1059770342** [justadudewhohacks/opencv4nodejs#594]
module.js:681
  return process.dlopen(module, path._makeLong(filename));
                 ^

Error: /www/wwwroot/http/capture_update2/node_modules/opencv4nodejs/build/Release/opencv4nodejs.node: invali
    at Object.Module._extensions..node (module.js:681:18)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/www/wwwroot/http/capture_update2/node_modules/opencv4nodejs/lib/cv.js:17:8)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
I deploy opencv4nodejs in  my server, but when I run "node server.js", it comes to thoese kind of stuffs as shown above. PLZ help me, THX!!!

**Comment by justadudewhohacks** [comment]
You forgot to add the path to the OpenCV binaries (.dlls) to your system path, or the some binaries are not accessible by your system.

**Comment by Simon1059770342** [comment]
My OS is CentOS7.4.1708, so how can I add the path to the OpenCV binaries (.dlls) to my system path?

**Comment by justadudewhohacks** [comment]
Under CentOS you do not need to add the binaries to your system path like on windows. I am assuming you are using your own OpenCV installation? You likely forgot to link the OpenCV libraries as done [here](https://github.com/justadudewhohacks/opencv4nodejs-docker-images/blob/master/opencv/Dockerfile#L40-L41).

`sh -c 'echo "/usr/local/lib" > /etc/ld.so.conf.d/opencv.conf' && \
ldconfig && \`

**Comment by Simon1059770342** [comment]
My OS is exactly CentOS, but why this problem happened to me?

**Comment by Simon1059770342** [comment]
I don't use my own OpenCV installation
