### ISSUE TITLE
cv.QRCodeDetector is not a function

### ISSUE THREAD

**Issue by webzhd** [justadudewhohacks/opencv4nodejs#600]
error:
``` js
const qrDecoder = cv.QRCodeDetector()
                     ^

TypeError: cv.QRCodeDetector is not a function
    at Object.<anonymous> (e:\auto\auto-control\test.js:8:22)
    at Module._compile (internal/modules/cjs/loader.js:776:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:829:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)
```

code: 
```js
const cv = require('opencv4nodejs');
const inputImage = cv.imread("xxx.jpg")
const qrDecoder = cv.QRCodeDetector()
```

**Comment by justadudewhohacks** [comment]
The binding for `cv.QRCodeDetector` is not implemented. Happy to take PRs.
