### ISSUE TITLE
Error: VideoCapture::New - failed to open capture running with docker

### ISSUE THREAD

**Issue by chinesebug** [justadudewhohacks/opencv4nodejs#620]
# Auto Build - Full Error Log
Newbie trying to use docker-compose build, Please help. Code was running ok without docker. Changed a few lines to run docker.

I set import like the examples `global.cv = require(' /usr/lib/node_modules/opencv4nodejs')` and I used `FROM justadudewhohacks/opencv-nodejs:node9-opencv3.4.1-contrib` in the Dockerfile. I also deleted the line from package.json file. But I get following error 
```
 const wCap = new cv.VideoCapture(0);
docker_seller |              ^
docker_seller | 
docker_seller | Error: VideoCapture::New - failed to open capture
docker_seller |     at Object.<anonymous> (/seller/index.js:11:14)
docker_seller |     at Module._compile (module.js:649:30)
docker_seller |     at Object.Module._extensions..js (module.js:660:10)
docker_seller |     at Module.load (module.js:561:32)
docker_seller |     at tryModuleLoad (module.js:501:12)
docker_seller |     at Function.Module._load (module.js:493:3)
docker_seller |     at Function.Module.runMain (module.js:690:10)
docker_seller |     at startup (bootstrap_node.js:194:16)
docker_seller |     at bootstrap_node.js:666:3

```

*OpenCV version* v10.16.1

*With OpenCV-contrib?* (extra modules): yes/no?

*OS*:  MacOSX

**Comment by goulash1971** [comment]
@chinesebug could you post your Dockerfile and `docker start` command, also the JavaScript that invokes `new VideoCapture` (e.g. what is the file you are opening) etc.

**Comment by chinesebug** [comment]
@goulash1971 yes. thank you! I used `docker-compose build` and `docker-compose up`
Dockerfile
```
FROM justadudewhohacks/opencv-nodejs:node9-opencv3.4.1-contrib

#FROM m03geek/opencv-dlib-node:alpine
#RUN apk update && apk add -u --no-cache python make g++
#RUN npm i opencv4nodejs

WORKDIR /seller

COPY package*.json ./

RUN npm install

COPY . .

EXPOSE 3000

CMD [ "node", "index.js" ]
```
Dockercompose 
```
version: '3'

services:
  seller:
    container_name: docker_seller
    build: seller/
    ports:
      - '3000:3000'
    depends_on:
      - buyer
  buyer:
    container_name: docker_buyer
    build: buyer/
    ports:
      - '8080:8080'
```
The capture part of js
```
global.cv = require('/usr/lib/node_modules/opencv4nodejs')
const path = require('path');
//const express = require('express');
//const app = express();
//const server = require('http').Server(app);
const io = require('socket.io').listen(3000);
const iota = require('./iotaModule');

const FPS = 15;
const wCap = new cv.VideoCapture(0);

var payment_granularity = 90;
var cost = 2;
wCap.set(cv.CAP_PROP_FRAME_WIDTH,300);
wCap.set(cv.CAP_PROP_FRAME_HEIGHT,300);

io.sockets.on('connection',(socket) =>{
  console.log('Connected to client!')
  var imageCount = 0;
  var isPaused = 0;

  setInterval(() => {
    //console.log('count:',imageCount)
    //console.log('paused:',isPaused)
    if(isPaused == 0){
      if(imageCount == payment_granularity){
        isPaused = 1;
        console.log('*** Paused, wait for payment ***')
        socket.emit('DATA_INVOICE', payment_granularity);
      }
      const frame = wCap.read();
      const image = cv.imencode('.jpg',frame).toString('base64');
      socket.emit('image',image);
      imageCount++;
    }
  }, 1000/FPS)
```

**Comment by goulash1971** [comment]
@chinesebug try mapping your video device into your container  with `docker-composer ...

```
devices:
  - /dev/video0:/dev/video0
```

Or append to the `docker run` command ...

```
--device=/dev/video0:/dev/video0
```

**Comment by chinesebug** [comment]
@goulash1971 thanks! I tried put the line in `docker-compose` but it seems not able to find the camera. could this be macbook related? 
```
ERROR: for seller  Cannot start service seller: error gathering device information while adding custom device "/dev/video0": no such file or directory
```

**Comment by goulash1971** [comment]
@chinesebug yes looks like it's OSX specific ...

https://apple.stackexchange.com/questions/265281/using-webcam-connected-to-macbook-inside-a-docker-container

... there is some stuff on there about using AVFoundation, VLC etc bu not sure any of that will help when you're inside of OpenCV ...

I've just tried this `gst-launch-1.0 autovideosrc device=/dev/video0 ! autovideosink` (on a McPro) and that works fine, so (assuming that you have `gstreamer` installed) you could specify a `gstreamer` pipeline to `VideoCapture` with an `appsink` pad at the end.

**Comment by chinesebug** [comment]
@goulash1971 Yeah, looks so. Thanks for helping me still!

**Comment by goulash1971** [comment]
@chinesebug no problem ... I've received a lot of help from various people on this project so very happy to do what I can to help others.

Will be keen to see if / how you solve this problem - we use a `/dev/video0` on some Raspberry Pi Zeros that are used as "capture" nodes in out solution and then `gstreamer` off them to other nodes.

Even during development we've used the Pi's so never needed to use the WebCam on any of the Mac's
