### ISSUE TITLE
npm install opencv4nodejs build error

### ISSUE THREAD

**Issue by keen9012** [justadudewhohacks/opencv4nodejs#630]
# Error Message

gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:258:23)
gyp ERR! stack     at emitTwo (events.js:135:13)
gyp ERR! stack     at ChildProcess.emit (events.js:224:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:12)
gyp ERR! System Linux 3.10.0-693.el7.x86_64
gyp ERR! command "/usr/local/node/node-linux-x64/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--jobs" "max"
gyp ERR! cwd /usr/local/node/node-linux-x64/lib/node_modules/opencv4nodejs
gyp ERR! node -v v9.0.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok 
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! opencv4nodejs@5.2.0 install: `node-gyp rebuild --jobs max`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the opencv4nodejs@5.2.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2019-09-16T07_04_47_318Z-debug.log

# Auto Build - Full Error Log

*OpenCV version* (example 3.4.1): 3.4.6

*With OpenCV-contrib?* (extra modules): yes

*OS*: Windows 7 / 8 / 10? / MacOSX? / Ubuntu? Linux version 3.10.0-693.el7.x86_64 (builder@kbuilder.dev.centos.org) (gcc version 4.8.5 20150623 (Red Hat 4.8.5-16)

**Comment by keen9012** [comment]
[opencv4nodejs.txt](https://github.com/justadudewhohacks/opencv4nodejs/files/3619264/opencv4nodejs.txt)
