### ISSUE TITLE
error on `const cv = require('opencv4nodejs');`

### ISSUE THREAD

**Issue by nwheatle** [justadudewhohacks/opencv4nodejs#638]
Writing `const cv = require('opencv4nodejs');` in my server.js file crashes my app at startup.

Ubuntu - 18.04.3
node - 10.16.3
npm - 6.9.0
opencv4nodejs - 5.3.0

I installed with autobuild
`$ npm install opencv4nodejs` 

```
$ ls node_modules/ | grep open
opencv4nodejs
opencv-buils
```
```
$ npm start

> backend@1.0.0 start /home/nicole/Documents/practice/sdsnode/backend
> node server.js

/home/nicole/Documents/practice/sdsnode/backend/node_modules/opencv4nodejs/lib/cv.js:79
    throw err;
    ^

Error: /usr/lib/x86_64-linux-gnu/libatk-1.0.so.0: undefined symbol: g_log_structured_standard
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:807:18)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/home/nicole/Documents/practice/sdsnode/backend/node_modules/opencv4nodejs/lib/cv.js:72:8)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! backend@1.0.0 start: `node server.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the backend@1.0.0 start script.
```

looking at node_modules/opencv4nodejs/lib/cv.js:79
```
69  let cv = null;
70  try {
71    logDebug("require", "require path is " + requirePath);
72    cv = require(requirePath);
73  } catch (err) {
74    logDebug("require", "failed to require cv with exception: " + err.toString());
75    logDebug("require", "attempting to add opencv binaries to path");
76
77    if (!process.env.path) {
78      logDebug("require", "there is no path environment variable, skipping...");
79      throw err;
80   }
```
It looks like `cv = require(requirePath)` call fails, and then since there is no process.env.path, error is thrown:

requirePath was set to `/home/nicole/Documents/practice/sdsnode/backend/node_modules/opencv4nodejs/build/Release/opencv4nodejs`

Here is the error it throws:
`Error: /usr/lib/x86_64-linux-gnu/libatk-1.0.so.0: undefined symbol: g_log_structured_standard`

```
$ grep -l    g_log_structured_standard    /usr/lib/x86_64-linux-gnu/lib*

/usr/lib/x86_64-linux-gnu/libatk-1.0.so
/usr/lib/x86_64-linux-gnu/libatk-1.0.so.0
/usr/lib/x86_64-linux-gnu/libatk-1.0.so.0.22810.1
grep: /usr/lib/x86_64-linux-gnu/libcanberra-0.30: Is a directory
grep: /usr/lib/x86_64-linux-gnu/libfakeroot: Is a directory
/usr/lib/x86_64-linux-gnu/libgdk-3.so
/usr/lib/x86_64-linux-gnu/libgdk-3.so.0
/usr/lib/x86_64-linux-gnu/libgdk-3.so.0.2200.30
grep: /usr/lib/x86_64-linux-gnu/libglade: Is a directory
/usr/lib/x86_64-linux-gnu/libglib-2.0.a
/usr/lib/x86_64-linux-gnu/libglib-2.0.so
/usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
/usr/lib/x86_64-linux-gnu/libglib-2.0.so.0.5600.4
grep: /usr/lib/x86_64-linux-gnu/libgnome-desktop-3-17: Is a directory
grep: /usr/lib/x86_64-linux-gnu/libgphoto2: Is a directory
grep: /usr/lib/x86_64-linux-gnu/libgphoto2_port: Is a directory
grep: /usr/lib/x86_64-linux-gnu/libgtk2.0-0: Is a directory
grep: /usr/lib/x86_64-linux-gnu/libgtk-3-0: Is a directory
/usr/lib/x86_64-linux-gnu/libgtk-3.so
/usr/lib/x86_64-linux-gnu/libgtk-3.so.0
/usr/lib/x86_64-linux-gnu/libgtk-3.so.0.2200.30
grep: /usr/lib/x86_64-linux-gnu/libibverbs: Is a directory
grep: /usr/lib/x86_64-linux-gnu/libpeas-1.0: Is a directory
grep: /usr/lib/x86_64-linux-gnu/libproxy: Is a directory
grep: /usr/lib/x86_64-linux-gnu/libunity: Is a directory
grep: /usr/lib/x86_64-linux-gnu/libv4l: Is a directory
grep: /usr/lib/x86_64-linux-gnu/libv4lconvert0: Is a directory
```
I could not look inside the `/usr/lib/x86_64-linux-gnu/libatk-1.0.so.0
/usr/lib/x86_64-linux-gnu/libatk-1.0.so.0` file because it was not normal text. 

Does anyone have a clue what is wrong?

**Comment by nwheatle** [comment]
OK. I fixed it by restarting the computer, making an entirely new directory, making sure my default node version is the one I expect, reinstalling and building a new app. 

```
$ nvm alias default --lts
$ mkdir newDir
$ cd newDir
$ npm init -y
$ npm i express opencv4nodejs
```
#index.js
```
 const cv = require('opencv4nodejs');
 console.log('this worked')
```

```
$ node index.js

this worked
```

I had previously uninstalled/reinstalled/etc in the old directory, but it didn't help. Maybe the json-lock file was problematic? I don't know. I'll close the issue.
