### ISSUE TITLE
cuda decode with opencv4nodejs

### ISSUE THREAD

**Issue by huanvliu** [justadudewhohacks/opencv4nodejs#646]
question: I want to use GPU, the VideoReader is needed?can I compile cuda with opencv4nodejs?
now i get the error:
fatal error: opencv2/cudacodec.hpp: No such file or directory

# Manual Build - Environment Information

*OpenCV version* (example 3.4.6)

Ubuntu16.04

**Comment by huanvliu** [comment]
i set export OPENCV4NODEJS_AUTOBUILD_FLAGS=-DWITH_CUDA=ON;
then I npm  install opencv4nodejs;
but opencv build faild :

821 verbose lifecycle opencv-build@0.1.9~install: unsafe-perm in lifecycle true
822 verbose lifecycle opencv-build@0.1.9~install: PATH: /root/.nvm/versions/node/v10.16.3/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/root/.nvm/versions/node/v10.16.3/lib/node_modules/opencv4nodejs/node_modules/opencv-build/node_modules/.bin:/root/.nvm/versions/node/v10.16.3/lib/node_modules/opencv4nodejs/node_modules/.bin:/root/.nvm/versions/node/v10.16.3/lib/node_modules/.bin:/root/.nvm/versions/node/v10.16.3/bin:/usr/local/cuda/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
823 verbose lifecycle opencv-build@0.1.9~install: CWD: /root/.nvm/versions/node/v10.16.3/lib/node_modules/opencv4nodejs/node_modules/opencv-build
824 silly lifecycle opencv-build@0.1.9~install: Args: [ '-c', 'node ./install.js' ]
825 silly lifecycle opencv-build@0.1.9~install: Returned: code: 1  signal: null
826 info lifecycle opencv-build@0.1.9~install: Failed to exec install script
827 timing action:install Completed in 112784ms
828 verbose unlock done using /root/.npm/_locks/staging-f89b57f6c13ff91b.lock for /root/.nvm/versions/node/v10.16.3/lib/node_modules/.staging
829 timing stage:rollbackFailedOptional Completed in 1188ms
830 timing stage:runTopLevelLifecycles Completed in 115669ms
831 verbose stack Error: opencv-build@0.1.9 install: `node ./install.js`
831 verbose stack Exit status 1
831 verbose stack     at EventEmitter.<anonymous> (/root/.nvm/versions/node/v10.16.3/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:301:16)
831 verbose stack     at EventEmitter.emit (events.js:198:13)
831 verbose stack     at ChildProcess.<anonymous> (/root/.nvm/versions/node/v10.16.3/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
831 verbose stack     at ChildProcess.emit (events.js:198:13)
831 verbose stack     at maybeClose (internal/child_process.js:982:16)
831 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
832 verbose pkgid opencv-build@0.1.9
833 verbose cwd /root
834 verbose Linux 4.4.0-1092-aws
835 verbose argv "/root/.nvm/versions/node/v10.16.3/bin/node" "/root/.nvm/versions/node/v10.16.3/bin/npm" "i" "opencv4nodejs" "-g" "--unsafe-perm"
836 verbose node v10.16.3
837 verbose npm  v6.9.0
838 error code ELIFECYCLE
839 error errno 1
840 error opencv-build@0.1.9 install: `node ./install.js`
840 error Exit status 1
841 error Failed at the opencv-build@0.1.9 install script.
841 error This is probably not a problem with npm. There is likely additional logging output above.
842 verbose exit [ 1, true ]
