### ISSUE TITLE
Error: Cannot find module

### ISSUE THREAD

**Issue by Huaoe** [justadudewhohacks/opencv4nodejs#667]
Hi,

I have an issue when Iaunch yarn dev on my windows 10 machine.
Any help would be nice.

Thomas

S C:\Users\thoma\Documents\Projects\perso\Oozzee\nextjs> yarn dev
yarn run v1.19.1
$ cross-env PORT=3000 node server.js
internal/modules/cjs/loader.js:797
    throw err;
    ^

Error: Cannot find module 'C:\Users\thoma\Documents\Projects\perso\Oozzee\nextjs\node_modules\opencv4nodejs\build\Release\opencv4nodejs'
Require stack:
- C:\Users\thoma\Documents\Projects\perso\Oozzee\nextjs\node_modules\opencv4nodejs\lib\cv.js
- C:\Users\thoma\Documents\Projects\perso\Oozzee\nextjs\node_modules\opencv4nodejs\lib\opencv4nodejs.js
- C:\Users\thoma\Documents\Projects\perso\Oozzee\nextjs\server.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:794:15)
    at Function.Module._load (internal/modules/cjs/loader.js:687:27)
    at Module.require (internal/modules/cjs/loader.js:849:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (C:\Users\thoma\Documents\Projects\perso\Oozzee\nextjs\node_modules\opencv4nodejs\lib\cv.js:58:8)    at Module._compile (internal/modules/cjs/loader.js:956:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:973:10)
    at Module.load (internal/modules/cjs/loader.js:812:32)
    at Function.Module._load (internal/modules/cjs/loader.js:724:14)
    at Module.require (internal/modules/cjs/loader.js:849:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (C:\Users\thoma\Documents\Projects\perso\Oozzee\nextjs\node_modules\opencv4nodejs\lib\opencv4nodejs.js:11:79)
    at Module._compile (internal/modules/cjs/loader.js:956:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:973:10)
    at Module.load (internal/modules/cjs/loader.js:812:32)
    at Function.Module._load (internal/modules/cjs/loader.js:724:14) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'C:\\Users\\thoma\\Documents\\Projects\\perso\\Oozzee\\nextjs\\node_modules\\opencv4nodejs\\lib\\cv.js',
    'C:\\Users\\thoma\\Documents\\Projects\\perso\\Oozzee\\nextjs\\node_modules\\opencv4nodejs\\lib\\opencv4nodejs.js',    
    'C:\\Users\\thoma\\Documents\\Projects\\perso\\Oozzee\\nextjs\\server.js'
  ]
}
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by pedroaf0** [comment]
@Huaoe I have the same problem, did you find any solution?



```shell
PS C:\Users\pedroaf01\Documents\GitHub\opencv> node .\index.js
internal/modules/cjs/loader.js:979
  throw err;
  ^

Error: Cannot find module 'C:\Users\pedroaf01\Documents\GitHub\opencv\node_modules\opencv4nodejs\build\Release\opencv4nodejs'
Require stack:
- C:\Users\pedroaf01\Documents\GitHub\opencv\node_modules\opencv4nodejs\lib\cv.js
- C:\Users\pedroaf01\Documents\GitHub\opencv\node_modules\opencv4nodejs\lib\opencv4nodejs.js
- C:\Users\pedroaf01\Documents\GitHub\opencv\index.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:976:15)
    at Function.Module._load (internal/modules/cjs/loader.js:859:27)
    at Module.require (internal/modules/cjs/loader.js:1036:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (C:\Users\pedroaf01\Documents\GitHub\opencv\node_modules\opencv4nodejs\lib\cv.js:58:8)
    at Module._compile (internal/modules/cjs/loader.js:1147:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1167:10)
    at Module.load (internal/modules/cjs/loader.js:996:32)
    at Function.Module._load (internal/modules/cjs/loader.js:896:14)
    at Module.require (internal/modules/cjs/loader.js:1036:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'C:\\Users\\pedroaf01\\Documents\\GitHub\\opencv\\node_modules\\opencv4nodejs\\lib\\cv.js',
    'C:\\Users\\pedroaf01\\Documents\\GitHub\\opencv\\node_modules\\opencv4nodejs\\lib\\opencv4nodejs.js',
    'C:\\Users\\pedroaf01\\Documents\\GitHub\\opencv\\index.js'
  ]
}
```

I reinstalled with yarn and:
```shell
PS C:\Users\pedroaf01\Documents\GitHub\opencv> node .\index.js
internal/modules/cjs/loader.js:1197
  return process.dlopen(module, path.toNamespacedPath(filename));
                 ^

Error: error: 126\\?\C:\Users\pedroaf01\Documents\GitHub\opencv\node_modules\opencv4nodejs\build\Release\opencv4nodejs.node
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1197:18)
    at Module.load (internal/modules/cjs/loader.js:996:32)
    at Function.Module._load (internal/modules/cjs/loader.js:896:14)
    at Module.require (internal/modules/cjs/loader.js:1036:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (C:\Users\pedroaf01\Documents\GitHub\opencv\node_modules\opencv4nodejs\lib\cv.js:58:8)
    at Module._compile (internal/modules/cjs/loader.js:1147:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1167:10)
    at Module.load (internal/modules/cjs/loader.js:996:32)
    at Function.Module._load (internal/modules/cjs/loader.js:896:14)
```

**Comment by andronov04** [comment]
The same
