### ISSUE TITLE
Problem in using node v10.16.3

### ISSUE THREAD

**Issue by harry-wilson** [justadudewhohacks/opencv4nodejs#671]
I've installed opencv4nodejs 5.5.0 using `npm install --save opencv4nodejs` on my Ubuntu running node v10.16.3 and npm 6.9.0 but on invoking the module it throws the following error:

`Error: The module '/home/nasser/scripts/google_traffic/node_modules/opencv4nodejs/build/Release/opencv4nodejs.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 48. This version of Node.js requires
NODE_MODULE_VERSION 64. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`).
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:807:18)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/home/nasser/scripts/google_traffic/node_modules/opencv4nodejs/lib/cv.js:40:8)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)`.

I can't downgrade to node v6 because other node modules won't work in this version. How can I resolve this problem?

**Comment by lionel590** [comment]
Hi Harry was facing teh same issue > I suggest that you look at your env variable, see https://gist.github.com/adwellj/61e7f202bcfe5b96f312293e9c812ca6#gistcomment-2961489
it did fix my problem

**Comment by harry-wilson** [comment]
I've just build opencv from official site and build it. after adding dependency in package.json like the following but it gives me the error:

`"opencv4nodejs": {
    "disableAutoBuild": 1,
    "opencvIncludeDir": "/home/nasser/opencv/build/include",
    "opencvLibDir": "/home/nasser/opencv/build/lib",
    "opencvBinDir": "/home/nasser/opencv/build/bin"
  }` 

The error on **_npm install opencv4js_**:

`ERR! Error: Command failed: node-gyp rebuild --jobs max
In file included from ../cc/calib3d/calib3d.h:1:0,
                 from ../cc/opencv4nodejs.cc:7:
../cc/calib3d/calib3dBindings.h:2:10: fatal error: opencv2/calib3d.hpp: No such file or directory
 #include <opencv2/calib3d.hpp>
          ^~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make: *** [Release/obj.target/opencv4nodejs/cc/opencv4nodejs.o] Error 1
make: *** Waiting for unfinished jobs....
`
