### ISSUE TITLE
error when running the electron-rebuild -w opencv4nodejs

### ISSUE THREAD

**Issue by darknblack** [justadudewhohacks/opencv4nodejs#695]
```
0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   '/usr/local/Cellar/node/11.11.0/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'run',
1 verbose cli   'electron-rebuild'
1 verbose cli ]
2 info using npm@6.13.4
3 info using node@v12.16.1
4 verbose run-script [ 'preelectron-rebuild', 'electron-rebuild', 'postelectron-rebuild' ]
5 info lifecycle photobooth@0.1.0~preelectron-rebuild: photobooth@0.1.0
6 info lifecycle photobooth@0.1.0~electron-rebuild: photobooth@0.1.0
7 verbose lifecycle photobooth@0.1.0~electron-rebuild: unsafe-perm in lifecycle true
8 verbose lifecycle photobooth@0.1.0~electron-rebuild: PATH: /usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/Users/ianoderon/Desktop/dev/photobooth/node_modules/.bin://Users/ianoderon/Library/Android/sdk/emulator:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/Caskroom/android-sdk/:/usr/local/Caskroom/android-platform-tools/:/Library/Frameworks/Mono.framework/Versions/Current/Commands:/usr/local/git/bin:/usr/local/bin:/.composer/vendor/bin:/Users/ianoderon/.composer:/Users/ianoderon/Library/Android/sdk/tools:/Users/ianoderon/Library/Android/sdk/platform-tools:/Users/ianoderon/bin:/Applications/Visual Studio Code.app/Contents/Resources/app/bin
9 verbose lifecycle photobooth@0.1.0~electron-rebuild: CWD: /Users/ianoderon/Desktop/dev/photobooth
10 silly lifecycle photobooth@0.1.0~electron-rebuild: Args: [ '-c', 'electron-rebuild -w opencv4nodejs' ]
11 silly lifecycle photobooth@0.1.0~electron-rebuild: Returned: code: 255  signal: null
12 info lifecycle photobooth@0.1.0~electron-rebuild: Failed to exec electron-rebuild script
13 verbose stack Error: photobooth@0.1.0 electron-rebuild: `electron-rebuild -w opencv4nodejs`
13 verbose stack Exit status 255
13 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:311:20)
13 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:311:20)
13 verbose stack     at maybeClose (internal/child_process.js:1021:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
14 verbose pkgid photobooth@0.1.0
15 verbose cwd /Users/ianoderon/Desktop/dev/photobooth
16 verbose Darwin 18.7.0
17 verbose argv "/usr/local/Cellar/node/11.11.0/bin/node" "/usr/local/bin/npm" "run" "electron-rebuild"
18 verbose node v12.16.1
19 verbose npm  v6.13.4
20 error code ELIFECYCLE
21 error errno 255
22 error photobooth@0.1.0 electron-rebuild: `electron-rebuild -w opencv4nodejs`
22 error Exit status 255
23 error Failed at the photobooth@0.1.0 electron-rebuild script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 255, true ]

```
I'm using the following setup
Mac OSX 10.14.6
node v12.16.1
npm 6.13.4

**Comment by bgnq** [comment]
Hello

Same issue with : 
- Max OSX 10.15.5
- Node v12.10.0
- npm 6.10.3

OpenCv install with brew
Install et use with node it's OK
Build for Electron with electron-rebuild -w opencv4nodejs failed

Thanks !
