### ISSUE TITLE
NODE_MODULE_VERSION conflict. 

### ISSUE THREAD

**Issue by Shamim1977** [justadudewhohacks/opencv4nodejs#700]
Using:
OS: Win 10, x64
Electron: 6.1.9
OpenCV: 4.2.0
opencv4nodejs: 5.5.0

Tried this:
https://www.npmjs.com/package/opencv4nodejs
and this:
https://medium.com/@makearts/how-to-use-opencv4-on-electron-113b11623b7a

but the NODE_MODULE_VERSION conflict remains. 
Is anybody actually successful getting "opencv4nodejs" working?!! Any alternative to this?

Uncaught Error: The module '\\?\F:\ElectronWorks\OCVFace\node_modules\opencv4nodejs\build\Release\opencv4nodejs.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 72. This version of Node.js requires
NODE_MODULE_VERSION 73. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`).
    at process.func (electron/js2c/asar.js:138:31)
    at process.func [as dlopen] (electron/js2c/asar.js:138:31)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:828:18)
    at Object.func (electron/js2c/asar.js:138:31)
    at Object.func [as .node] (electron/js2c/asar.js:138:31)
    at Module.load (internal/modules/cjs/loader.js:645:32)
    at Function.Module._load (internal/modules/cjs/loader.js:560:12)
    at Module.require (internal/modules/cjs/loader.js:685:19)
    at require (internal/modules/cjs/helpers.js:16:16)
    at Object.<anonymous> (F:\ElectronWorks\OCVFace\node_modules\opencv4nodejs\lib\cv.js:58:8)

**Comment by ISebSej** [comment]
I have the same issue :(

Uncaught Error: The module '\\?\C:\OneDrive\WebApps\ManMachine\node_modules\opencv4nodejs\build\Release\opencv4nodejs.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 72. This version of Node.js requires
NODE_MODULE_VERSION 76. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`).
    at process.func (electron/js2c/asar.js:140)
    at process.func [as dlopen] (electron/js2c/asar.js:140)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1016)
    at Object.func (electron/js2c/asar.js:140)
    at Object.func [as .node] (electron/js2c/asar.js:140)
    at Module.load (internal/modules/cjs/loader.js:816)
    at Module._load (internal/modules/cjs/loader.js:728)
    at Module._load (electron/js2c/asar.js:717)
    at Function.Module._load (electron/js2c/asar.js:717)
    at Module.require (internal/modules/cjs/loader.js:853)

**Comment by ttttupup** [comment]
Got the same issue

Error: The module '\\?\E:\nodeProject\node_modules\opencv4nodejs\build\Release\opencv4nodejs.node'
  was compiled against a different Node.js version using
  NODE_MODULE_VERSION 72. This version of Node.js requires
  NODE_MODULE_VERSION 76. Please try re-compiling or re-installing
  the module (for instance, using `npm rebuild` or `npm install`).
      at process.func [as dlopen] (electron/js2c/asar.js:140:31)
      at Object.Module._extensions..node (internal/modules/cjs/loader.js:1016:18)
      at Object.func [as .node] (electron/js2c/asar.js:140:31)
      at Module.load (internal/modules/cjs/loader.js:816:32)
      at Module._load (internal/modules/cjs/loader.js:728:14)
      at Function.Module._load (electron/js2c/asar.js:748:26)
      at Module.require (internal/modules/cjs/loader.js:853:19)
      at require (internal/modules/cjs/helpers.js:74:18)
      at Object.<anonymous> (E:\nodeProject\jdSupport\node_modules\opencv4nodejs\lib\cv.js:58:8)
      at Module._compile (internal/modules/cjs/loader.js:968:30)
