### ISSUE TITLE
Gyp can't find opencv4nodejs.vcxproj

### ISSUE THREAD

**Issue by tothadi** [justadudewhohacks/opencv4nodejs#709]
I'm trying to install the package, and the output is as below. I can't provide error log, cause it's not created, as the installer says on the end that the package is updated. Updated becuase I'v tried to install several times. Clear install after deleting node_modules and package-lock, updating, etc.
At first clean install opencv-build built without errors, but in the end of the install the output was the same: 
"+ opencv4nodejs@5.5.0
installed 1 package and audited 489 packages in 12.343s
found 0 vulnerabilities"

But it's not working, casue my scripts can't find the module.

Opencv lib, bin, include have been set. Everything is in the right folder, no special charachters, spaces, etc.,
Bin dir included in path. Re-checked twice.

The bolded text means the system can't find the file (opencv4nodejs.vcxproj). But after this runs, the file can be found in the specified directory.

# Error Message

info the following opencv4nodejs environment variables are set in the package.json:
info disableAutoBuild: 1
info opencvIncludeDir: c:\dev\opencv-built-with-cuda\opencv\build\include
info opencvLibDir: c:\dev\opencv-built-with-cuda\opencv\build\x64\vc15\lib
info opencvBinDir: c:\dev\opencv-built-with-cuda\opencv\build\x64\vc15\bin
info install using lib dir: c:/dev/opencv-built-with-cuda/opencv/build/x64/vc15/lib
info install found the following libs:
info install core : c:\dev\opencv-built-with-cuda\opencv\build\x64\vc15\lib\opencv_core420.lib
info install highgui : c:\dev\opencv-built-with-cuda\opencv\build\x64\vc15\lib\opencv_highgui420.lib
info install imgcodecs : c:\dev\opencv-built-with-cuda\opencv\build\x64\vc15\lib\opencv_imgcodecs420.lib
info install imgproc : c:\dev\opencv-built-with-cuda\opencv\build\x64\vc15\lib\opencv_imgproc420.lib
info install features2d : c:\dev\opencv-built-with-cuda\opencv\build\x64\vc15\lib\opencv_features2d420.lib
info install calib3d : c:\dev\opencv-built-with-cuda\opencv\build\x64\vc15\lib\opencv_calib3d420.lib
info install photo : c:\dev\opencv-built-with-cuda\opencv\build\x64\vc15\lib\opencv_photo420.lib
info install objdetect : c:\dev\opencv-built-with-cuda\opencv\build\x64\vc15\lib\opencv_objdetect420.lib
info install ml : c:\dev\opencv-built-with-cuda\opencv\build\x64\vc15\lib\opencv_ml420.lib
info install video : c:\dev\opencv-built-with-cuda\opencv\build\x64\vc15\lib\opencv_video420.lib
info install videoio : c:\dev\opencv-built-with-cuda\opencv\build\x64\vc15\lib\opencv_videoio420.lib
info install videostab : c:\dev\opencv-built-with-cuda\opencv\build\x64\vc15\lib\opencv_videostab420.lib
info install dnn : c:\dev\opencv-built-with-cuda\opencv\build\x64\vc15\lib\opencv_dnn420.lib
info install face : c:\dev\opencv-built-with-cuda\opencv\build\x64\vc15\lib\opencv_face420.lib
info install text : c:\dev\opencv-built-with-cuda\opencv\build\x64\vc15\lib\opencv_text420.lib
info install tracking : c:\dev\opencv-built-with-cuda\opencv\build\x64\vc15\lib\opencv_tracking420.lib
info install xfeatures2d : c:\dev\opencv-built-with-cuda\opencv\build\x64\vc15\lib\opencv_xfeatures2d420.lib
info install ximgproc : c:\dev\opencv-built-with-cuda\opencv\build\x64\vc15\lib\opencv_ximgproc420.lib

info install setting the following defines:
info defines OPENCV4NODEJS_FOUND_LIBRARY_CORE
info defines OPENCV4NODEJS_FOUND_LIBRARY_HIGHGUI
info defines OPENCV4NODEJS_FOUND_LIBRARY_IMGCODECS
info defines OPENCV4NODEJS_FOUND_LIBRARY_IMGPROC
info defines OPENCV4NODEJS_FOUND_LIBRARY_FEATURES2D
info defines OPENCV4NODEJS_FOUND_LIBRARY_CALIB3D
info defines OPENCV4NODEJS_FOUND_LIBRARY_PHOTO
info defines OPENCV4NODEJS_FOUND_LIBRARY_OBJDETECT
info defines OPENCV4NODEJS_FOUND_LIBRARY_ML
info defines OPENCV4NODEJS_FOUND_LIBRARY_VIDEO
info defines OPENCV4NODEJS_FOUND_LIBRARY_VIDEOIO
info defines OPENCV4NODEJS_FOUND_LIBRARY_VIDEOSTAB
info defines OPENCV4NODEJS_FOUND_LIBRARY_DNN
info defines OPENCV4NODEJS_FOUND_LIBRARY_FACE
info defines OPENCV4NODEJS_FOUND_LIBRARY_TEXT
info defines OPENCV4NODEJS_FOUND_LIBRARY_TRACKING
info defines OPENCV4NODEJS_FOUND_LIBRARY_XFEATURES2D
info defines OPENCV4NODEJS_FOUND_LIBRARY_XIMGPROC

info install setting the following includes:
info includes c:/dev/opencv-built-with-cuda/opencv/build/include

info install setting the following libs:
info libs c:/dev/opencv-built-with-cuda/opencv/build/x64/vc15/lib/opencv_core420.lib
info libs c:/dev/opencv-built-with-cuda/opencv/build/x64/vc15/lib/opencv_highgui420.lib
info libs c:/dev/opencv-built-with-cuda/opencv/build/x64/vc15/lib/opencv_imgcodecs420.lib
info libs c:/dev/opencv-built-with-cuda/opencv/build/x64/vc15/lib/opencv_imgproc420.lib
info libs c:/dev/opencv-built-with-cuda/opencv/build/x64/vc15/lib/opencv_features2d420.lib
info libs c:/dev/opencv-built-with-cuda/opencv/build/x64/vc15/lib/opencv_calib3d420.lib
info libs c:/dev/opencv-built-with-cuda/opencv/build/x64/vc15/lib/opencv_photo420.lib
info libs c:/dev/opencv-built-with-cuda/opencv/build/x64/vc15/lib/opencv_objdetect420.lib
info libs c:/dev/opencv-built-with-cuda/opencv/build/x64/vc15/lib/opencv_ml420.lib
info libs c:/dev/opencv-built-with-cuda/opencv/build/x64/vc15/lib/opencv_video420.lib
info libs c:/dev/opencv-built-with-cuda/opencv/build/x64/vc15/lib/opencv_videoio420.lib
info libs c:/dev/opencv-built-with-cuda/opencv/build/x64/vc15/lib/opencv_videostab420.lib
info libs c:/dev/opencv-built-with-cuda/opencv/build/x64/vc15/lib/opencv_dnn420.lib
info libs c:/dev/opencv-built-with-cuda/opencv/build/x64/vc15/lib/opencv_face420.lib
info libs c:/dev/opencv-built-with-cuda/opencv/build/x64/vc15/lib/opencv_text420.lib
info libs c:/dev/opencv-built-with-cuda/opencv/build/x64/vc15/lib/opencv_tracking420.lib
info libs c:/dev/opencv-built-with-cuda/opencv/build/x64/vc15/lib/opencv_xfeatures2d420.lib
info libs c:/dev/opencv-built-with-cuda/opencv/build/x64/vc15/lib/opencv_ximgproc420.lib
info install spawning node gyp process: node-gyp rebuild --jobs max

C:\dev\rdf-merleg\node_modules\opencv4nodejs>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild --jobs max )  else (node "C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild --jobs max )
TRACKER : error TRK0005: Failed to locate: "CL.exe". **A rendszer nem tal�lja a megadott f�jlt. [C:\dev\rdf-merleg\node_modules\opencv4nodejs\build\opencv4nodejs.vcxproj]**

gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\MSBuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:210:5)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)
gyp ERR! System Windows_NT 10.0.14393
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--jobs" "max"
gyp ERR! cwd C:\dev\rdf-merleg\node_modules\opencv4nodejs
gyp ERR! node -v v12.13.1
gyp ERR! node-gyp -v v5.0.5
gyp ERR! not ok
ERR! Error: Command failed: node-gyp rebuild --jobs max
gyp ERR! build error 
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\MSBuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:210:5)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)
gyp ERR! System Windows_NT 10.0.14393
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--jobs" "max"
gyp ERR! cwd C:\dev\rdf-merleg\node_modules\opencv4nodejs
gyp ERR! node -v v12.13.1
gyp ERR! node-gyp -v v5.0.5
gyp ERR! not ok 

npm WARN rdf-merleg@1.2.0 No repository field.
npm WARN rdf-merleg@1.2.0 No license field.

+ opencv4nodejs@5.5.0
updated 1 package and audited 489 packages in 12.343s
found 0 vulnerabilities

# Environment

*OpenCV version* (example 3.4.1): 4.2.0

*With OpenCV-contrib?* (extra modules): yes?

*OS*: Windows Server 2016

**Comment by tothadi** [comment]
Sorry, I didn't mention, about a month ago I succesfully installed with autobuild on the same system.
Also, two days ago I succesfully installed it with autobuild on my win10 notebook.  The only difference is my notebook doesn't have cuda. But I don't think it's related.

**Comment by GrapeCandy** [comment]
I have the same problem...
I'd appreciate it if someone could give me the answer.
