### ISSUE TITLE
Cannot convert undefined or null to object at Function.keys (<anonymous>) (Testing)

### ISSUE THREAD

**Issue by MiguelTMoreira** [justadudewhohacks/opencv4nodejs#723]
I'm using the matchFeature example, works fine. But i needed to do some changes i order to work for my project but when i want to do test the following error occurs:

test/matchFeature.test.js

  ● Test suite failed to run

    TypeError: Cannot convert undefined or null to object
        at Function.keys (<anonymous>)

      at Object.<anonymous> (node_modules/opencv4nodejs/lib/cv.js:63:8)
      at Object.<anonymous> (node_modules/opencv4nodejs/lib/opencv4nodejs.js:11:79)

I think is a problem when loading the module, but i cant fix it.
I'm using Jest for testing.

**Comment by MiguelTMoreira** [comment]
If i run with node

[https://prnt.sc/sq41s9](url)  

And if i run test with jest:

[https://prnt.sc/sq42mb](url)
