### ISSUE TITLE
[WINDOWS 10][ELECTRON][REBUILD][C1083][LNK2001][SOLVED]

### ISSUE THREAD

**Issue by elpaxel** [justadudewhohacks/opencv4nodejs#746]
That is not a issue. Just tips for anyone that straggling like me.

Before the start i need to say that i tried every solution that found in there and in google and only manual editing of the binding.gyp helped me. I tried setting folders in env variables etc. Why I mention this I will explain in the end.

Tested on Windows 10, Python 2.7, MS Build Tools 2017.

If you trying to rebuild "opencv4nodejs" for Electron (maybe other similar soft) and getting "**C1083**" errors (many-many errors):

1. Check if you have **white-spaces** in your project path and delete them if any.
2. Go to (YOUR PROJECT)\node_modules\opencv4nodejs and edit **binding.gyp** file:
    Add **"../opencv-build/opencv/build/include"** to the **"include_dirs"** array.

After this you will likely get "**LNK2001**" errors on rebuild. To fix this:

1. Go to (YOUR PROJECT)\node_modules\opencv4nodejs and edit **binding.gyp** file (again):
    Add **every** .lib file from (YOUR PROJECT)\node_modules\opencv-build\opencv\build\x64\vc15\lib\ to the **"libraries"** array.

    Format of the path needs to be like this:
    "(FULL PATH TO YOUR PROJECT)\\\\node_modules\\\\opencv-build\\\\opencv\\\\build\\\\x64\\\\vc15\\\\lib\\\\opencv_calib3d346"

    Don't forget to escape every **"\\"** like in the example path above - **"\\\\"**.

The final look:

![Capture](https://user-images.githubusercontent.com/45597512/89099480-4323ef00-d3f8-11ea-93db-aa20e44e54da.PNG)

And now explanation why I mentioned that I tried setting folders in env. Because the manual steps that I've done is automated in binding.gyp. But they are clearly not working. I can assume that problem is in install.js file. Because when parseEnv.js trying to fetch OPENCV4NODEJS_INCLUDES or OPENCV4NODEJS_LIBRARIES they are empty. I will check it out later but I can be wrong so don't expect anything ;)

**Comment by sajithgr** [comment]
After electron-rebuild are you able to load opencv4nodejs in your project? if so please help.

**Comment by elpaxel** [comment]
Yep all is working in electron. Just follow the steps in my instruction and you good to go.

**Comment by Zoubi-maker** [comment]
Hi, thanks for this fix. Im now able to rebuild with electron, but I get an error 126 when I require the module.

`Error: error: 126\\?\C:\Users\u\Documents\project\node_modules\opencv4nodejs\build\Release\opencv4nodejs.node
    at process.func [as dlopen] (electron/js2c/asar.js:140:31)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1034:18)
    at Object.func [as .node] (electron/js2c/asar.js:140:31)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Module._load (internal/modules/cjs/loader.js:727:14)
    at Function.Module._load (electron/js2c/asar.js:769:28)
    at Module.require (internal/modules/cjs/loader.js:852:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (C:\Users\u\Documents\project\node_modules\opencv4nodejs\lib\cv.js:58:8)
    at Module._compile (internal/modules/cjs/loader.js:967:30)`

**Comment by elpaxel** [comment]
I ran across this error (version mismatch) several times in different projects. Here's what you can try:
Install last version (stable) of electron and electron-rebuild.
OR
Remove electron from global packages. Sometimes there is a bug when you need to delete electron from other projects.
OR
If you have NVM (node version manager) then delete all versions except from the one you use.
OR
Try to build for specific version (check the electron-rebuild docs for more details). But it is rarely helping and hard to "guess" the right version.

And there is more ways of fixing this error because usually this error can be anything. Basically you see this error because electron uses non-standard version number on its Node.JS core. So good luck and may the Google be with you.

**Comment by Zoubi-maker** [comment]
Im able to make it work when i launch electron from an admin terminal.

When i do: npm list -g, its empty, for regular user and admin.
I dont have NVM.
I already tried reinstalling electron and rebuild alot of times.

What is weird to me is that it talks about a node_module_version 80 which I cant find a setup for on this page: https://nodejs.org/en/download/releases/

**Comment by elpaxel** [comment]
As I said Electron inside uses non-standard version number on its Node.JS core. There is the complete list somewhere on google.
Maybe you can use this [https://github.com/lgeiger/electron-abi](url) to list ABI (Node.JS core) versions of electron.

But I almost sure that the problem that you have not in specific version. I compiled my project with Node 12.18.0 LTS and Electron 9.0.0 and all is working after rebuild. But if you check main page of [https://www.electronjs.org/](url) there is Electron 9.2.0 that pointing on Node 12.14.1 and maybe try with this Node version for best compatibility.
