### ISSUE TITLE
new Error('library dir does not exist: ' + libDir)

### ISSUE THREAD

**Issue by 74staz** [justadudewhohacks/opencv4nodejs#806]
Hello, I have been trying to install opencv4nodejs on MacOS Mojave with npm i opencv4nodejs and it keeps giving me this error:

```
npm ERR! code 1
npm ERR! path /Users/u/trr/node_modules/opencv4nodejs
npm ERR! command failed
npm ERR! command sh -c node ./install/install.js
npm ERR! info install using lib dir: /Users/u/trr/node_modules/opencv-build/opencv/build/lib
npm ERR! /Users/u/trr/node_modules/opencv4nodejs/install/install.js:37
npm ERR!   throw new Error('library dir does not exist: ' + libDir)
npm ERR!   ^
npm ERR! 
npm ERR! Error: library dir does not exist: /Users/u/trr/node_modules/opencv-build/opencv/build/lib
npm ERR!     at Object.<anonymous> (/Users/u/trr/node_modules/opencv4nodejs/install/install.js:37:9)
npm ERR!     at Module._compile (node:internal/modules/cjs/loader:1092:14)
npm ERR!     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1121:10)
npm ERR!     at Module.load (node:internal/modules/cjs/loader:972:32)
npm ERR!     at Function.Module._load (node:internal/modules/cjs/loader:813:14)
npm ERR!     at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:76:12)
npm ERR!     at node:internal/main/run_main_module:17:47
```

Have tried so many things but it just wouldn't work. Would be great if someone can help me with this.

**Comment by KeitelDOG** [comment]
@74staz You might try this steps: https://github.com/justadudewhohacks/opencv4nodejs/issues/775#issuecomment-804347861

It will help you solve a lot. And then if your OpenCV installation is correct and matched opencv4nodejs version, than it will build fully.

**Comment by 74staz** [comment]
> @74staz You might try this steps: [#775 (comment)](https://github.com/justadudewhohacks/opencv4nodejs/issues/775#issuecomment-804347861)
> 
> It will help you solve a lot. And then if your OpenCV installation is correct and matched opencv4nodejs version, than it will build fully. But quickly, you can just disable auto build in terminal with : `export OPENCV4NODEJS_DISABLE_AUTOBUILD=1`. And after you will build it yourself.

Thanks a lot, this looks really detailed. I switched to Python to work with OpenCV, now I am gonna try this for NodeJS.

**Comment by 74staz** [comment]
Okay so I installed it on my Mac but when I run it via `require('opencv4nodejs')` it gives this error: 
```
/node_modules/opencv4nodejs/lib/cv.js:47
    throw err
    ^

Error: Cannot find module '/Users/u/trr/node_modules/opencv4nodejs/build/Release/opencv4nodejs'
```

The path exists but there is another folder "obj.target" like  `node_modules/opencv4nodejs/build/Release/obj.target/opencv4nodejs`. Someone please help, thank you.

**Comment by KeitelDOG** [comment]
@74staz the file hasn't been created. There is some error on the node-gyp build. When its created, it will be a `.node` file under Release.
`node_modules/opencv4nodejs/build/Release/oopencv4nodejs.node`.

**Comment by KeitelDOG** [comment]
@74staz follow my suggestion here https://github.com/justadudewhohacks/opencv4nodejs/issues/775#issuecomment-804347861

And this will increase greatly your chance to install it by understanding things better.

**Comment by KeitelDOG** [comment]
@74staz you might also try this if you want to use OpenCV 4.5.0:
httpss://github.com/justadudewhohacks/opencv4nodejs/issues/805#issuecomment-806314329

**Comment by Azperin** [comment]
1. `npm i -g npm@6`
2. `npm i opencv4nodejs --save`
3. `npm i -g npm@latest`

**Comment by staz9** [comment]
> 3\. `npm i -g npm@latest`

```
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! opencv-build@0.1.9 install: `node ./install.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the opencv-build@0.1.9 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

**Comment by Azperin** [comment]
add to `package.json`
```
"opencv4nodejs": {
	"disableAutoBuild": 1
} ```

**Comment by staz9** [comment]
> add to `package.json`
> 
> ```
> "opencv4nodejs": {
> 	"disableAutoBuild": 1
> } 
> ```

Ran into this now:
```
fatal error: too many errors emitted, stopping now [-ferror-limit=]
20 errors generated.
make: *** [Release/obj.target/opencv4nodejs/cc/tracking/MultiTracker.o] Error 1
2 warnings generated.
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/User/.nvm/versions/node/v14.15.4/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:315:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:277:12)
gyp ERR! System Darwin 18.7.0
gyp ERR! command "/Users/User/.nvm/versions/node/v14.15.4/bin/node" "/Users/User/.nvm/versions/node/v14.15.4/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--jobs" "max"
gyp ERR! cwd /Users/User/Desktop/test/node_modules/opencv4nodejs
gyp ERR! node -v v14.15.4
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok 
```

**Comment by Azperin** [comment]
Don't know how it works on Mac. Just install / build plain opencv. Make links in `package.json`, like mine, but with your paths:
```
"opencv4nodejs": {
"disableAutoBuild": 1,
"opencvIncludeDir": "R:\\OpenCV\\opencv\\build\\include",
"opencvLibDir": "R:\\OpenCV\\opencv\\build\\x64\\vc15\\lib",
"opencvBinDir": "R:\\OpenCV\\opencv\\build\\x64\\vc15\\bin",
"opencvDir": "R:\\OpenCV\\opencv\\build\\x64\\vc15"
} 
```
Then `npm i opencv4nodejs --save`

**Comment by Jiyvn** [comment]
```shell
export OPENCV4NODEJS_DISABLE_AUTOBUILD=1

npm install -g opencv-build         // you might get error occur, try to set opencv4nodejs flag(https://github.com/justadudewhohacks/opencv4nodejs/issues/775#issuecomment-878141077)
npm install -g opencv4nodejs      // you should encounter an error, leave it out
sudo ln -s $(npm root -g)/opencv-build $(npm root -g)/opencv4nodejs/node_modules       // create a link of opencv-build under $(npm root -g)/opencv4nodejs/node_modules. remove if already exists
cd $(npm root -g)/opencv4nodejs/
node install/install.js         // complie error should be meet, for me, it's `MultiTracker`
```
I finally got succeed after comment out `tracking` related dependencies and `xfeatures2d` related dependencies in `$(npm root -g)/opencv4nodejs/binding.gyp`.  

`$(npm root -g)/opencv4nodejs/build/Release/opencv4nodejs.node` will be generated, but unfortunately, I am not able to import `opencv4nodejs` module.

**Comment by ShawYN** [comment]
1. `brew update`

2. `brew install opencv@4`

3. `brew link --force opencv@4`

4. !!!NOTE!!! Please change the opencv version to fit your installation in step 3.
`export OPENCV4NODEJS_DISABLE_AUTOBUILD=1`
`export OPENCV_LIB_DIR=/opt/homebrew/Cellar/opencv/4.5.5_3/lib`
`export OPENCV_BIN_DIR=/opt/homebrew/Cellar/opencv/4.5.5_3/bin`
`export OPENCV_INCLUDE_DIR=/opt/homebrew/Cellar/opencv/4.5.5_3/include/opencv4`

5. `npm install -g opencv4nodejs`

**Comment by baibn** [comment]
> @74staz You might try this steps: [#775 (comment)](https://github.com/justadudewhohacks/opencv4nodejs/issues/775#issuecomment-804347861)
> 
> It will help you solve a lot. And then if your OpenCV installation is correct and matched opencv4nodejs version, than it will build fully. But quickly, you can just disable auto build in terminal with : `export OPENCV4NODEJS_DISABLE_AUTOBUILD=1`. And after you will build it yourself.

it dosen't work！
