### ISSUE TITLE
opencv4nodejs is installed， Try  examples：Error: The specified module could not be found.

### ISSUE THREAD

**Issue by minhuan520** [justadudewhohacks/opencv4nodejs#809]
D:\nodejs\node.exe E:\Project\web\Demo\open\public\open.js
internal/modules/cjs/loader.js:1206
  return process.dlopen(module, path.toNamespacedPath(filename));
                 ^

Error: The specified module could not be found.
\\?\E:\Project\web\Demo\open\node_modules\opencv4nodejs\build\Release\opencv4nodejs.node
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1206:18)
    at Module.load (internal/modules/cjs/loader.js:1000:32)
    at Function.Module._load (internal/modules/cjs/loader.js:899:14)
    at Module.require (internal/modules/cjs/loader.js:1042:19)
    at require (internal/modules/cjs/helpers.js:77:18)
    at Object.<anonymous> (E:\Project\web\Demo\open\node_modules\opencv4nodejs\lib\cv.js:58:8)
    at Module._compile (internal/modules/cjs/loader.js:1156:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1176:10)
    at Module.load (internal/modules/cjs/loader.js:1000:32)
    at Function.Module._load (internal/modules/cjs/loader.js:899:14)

Process finished with exit code 1

**Comment by minhuan520** [comment]
I had the same problem in the latest Vuecli, using the answer from upstairs, I did not have 'test'.Use: rule(/\.node$/)
.use('node-loader')
.loader('node-loader'), and NPM install node-loader, new issue Node-loader and vue-loader conflic

**Comment by minhuan520** [comment]
D:\nodejs\node.exe E:\Project\web\Demo\open\public\open.js
internal/modules/cjs/loader.js:1206
  return process.dlopen(module, path.toNamespacedPath(filename));
                 ^

Error: The specified module could not be found.
\\?\E:\Project\web\Demo\open\node_modules\opencv4nodejs\build\Release\opencv4nodejs.node
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1206:18)
    at Module.load (internal/modules/cjs/loader.js:1000:32)
    at Function.Module._load (internal/modules/cjs/loader.js:899:14)
    at Module.require (internal/modules/cjs/loader.js:1042:19)
    at require (internal/modules/cjs/helpers.js:77:18)
    at Object.<anonymous> (E:\Project\web\Demo\open\node_modules\opencv4nodejs\lib\cv.js:58:8)
    at Module._compile (internal/modules/cjs/loader.js:1156:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1176:10)
    at Module.load (internal/modules/cjs/loader.js:1000:32)
    at Function.Module._load (internal/modules/cjs/loader.js:899:14)

Process finished with exit code 1

**Comment by Minori-ty** [comment]
你解决了吗？

**Comment by zhbn** [comment]
怎么解决的

**Comment by Minori-ty** [comment]
> 怎么解决的

我写了个大致的步骤：https://juejin.cn/post/7083471826013126686
