### ISSUE TITLE
opencv4nodejs not installing with "library dir does not exist" error

### ISSUE THREAD

**Issue by christopheryeemonbymason** [justadudewhohacks/opencv4nodejs#814]
# Error Message
```
christopheryeemon@system76-pc:~$ npm i -g opencv4nodejs
npm ERR! code 1
npm ERR! path /home/christopheryeemon/.nvm/versions/node/v12.16.2/lib/node_modules/opencv4nodejs
npm ERR! command failed
npm ERR! command sh -c node ./install/install.js
npm ERR! info install using lib dir: /home/christopheryeemon/.nvm/versions/node/v12.16.2/lib/node_modules/opencv4nodejs/node_modules/opencv-build/opencv/build/lib
npm ERR! /home/christopheryeemon/.nvm/versions/node/v12.16.2/lib/node_modules/opencv4nodejs/install/install.js:37
npm ERR!   throw new Error('library dir does not exist: ' + libDir)
npm ERR!   ^
npm ERR! 
npm ERR! Error: library dir does not exist: /home/christopheryeemon/.nvm/versions/node/v12.16.2/lib/node_modules/opencv4nodejs/node_modules/opencv-build/opencv/build/lib
npm ERR!     at Object.<anonymous> (/home/christopheryeemon/.nvm/versions/node/v12.16.2/lib/node_modules/opencv4nodejs/install/install.js:37:9)
npm ERR!     at Module._compile (internal/modules/cjs/loader.js:1156:30)
npm ERR!     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1176:10)
npm ERR!     at Module.load (internal/modules/cjs/loader.js:1000:32)
npm ERR!     at Function.Module._load (internal/modules/cjs/loader.js:899:14)
npm ERR!     at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:74:12)
npm ERR!     at internal/main/run_main_module.js:18:47

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/christopheryeemon/.npm/_logs/2021-06-25T22_50_09_267Z-debug.
```

*OpenCV version* (example 3.4.1): 5.6.0

*With OpenCV-contrib?* (extra modules): no

*OS*: Ubuntu 20.04.2 LTS

**Comment by ammaramja** [comment]
Can this issue get attention from contributors, please?

**Comment by gitameditha** [comment]
yes I also get same issue on here

**Comment by koush** [comment]
Run this per the instructions:

`export OPENCV4NODEJS_DISABLE_AUTOBUILD=1`

**Comment by SaulSV2** [comment]
i found this as a solution:

1. install opencv with brew (follow the manual instalation in the README)
```
brew update
brew install opencv
brew link --force opencv
```
2. the link command should say where oopenvc was instalated, in my case was on usr/local/Cellar/opencv/4.5.3_2, so go to that location
3. install opencv opencv-build in the project
`npm install --save opencv-build`
4. that will create the opencv dir in the node_modules so go there and create manually the carpets /node_modules/opencv-build/opencv/build/
5. in the usr/local/Cellar/opencv/4.5.3_2 copy the lib carpet and paste it in /node_modules/opencv-build/opencv/build/

at least this way i could install opencv4nodejs, i hope this is help u <3

**Comment by BinaryJava** [comment]
I get the same issue even when running with the export command above

**Comment by jdmg94** [comment]
If you are running on a Unix system you could try to compile your own opencv that's pretty straight forward.
You can place the whole folder on the root of your node project and add to `package.json` the following:

```
"opencv4nodejs": {
    "disableAutoBuild": 1,
    "opencvIncludeDir": "../../opencv/include",
    "opencvLibDir": "../../opencv/lib",
    "opencvBinDir": "../../opencv/bin"
  }
```
While digging a little further into this issue I also found out that the logic for finding the opencv build is specific to windows, see this line: https://github.com/justadudewhohacks/opencv4nodejs/blob/master/lib/cv.js#L45

where `process.env.path` is found on windows, for unix systems its `process.env.PATH`, this could be fixed with little effort but the part that puzzle's me is that on the same catch block (and without really changing the requirePath) it goes on to call the same path that triggered the catch block to begin with, see this line: https://github.com/justadudewhohacks/opencv4nodejs/blob/master/lib/cv.js#L58

@justadudewhohacks  could you please get linux users some help please?

**Comment by CrimsonVex** [comment]
I'm also having this error. Windows 10. Nodejs version 16.13.1. No idea what to do with `export OPENCV4NODEJS_DISABLE_AUTOBUILD=1`

**Comment by doongsilee** [comment]
I don't understand why but after installing node-gyp it works.

`apt-get install --save node-gyp`
