### ISSUE TITLE
Unable to install: `library dir does not exist`

### ISSUE THREAD

**Issue by gamingredpandas** [justadudewhohacks/opencv4nodejs#837]
# Description
I am trying to use opencv4nodejs to capture my webcam, but I am not able to install it.
I tried a lot of other things and other ways to install opencv4nodejs, but none were successful, so I will just post the result of an auto build.

# Error Message
`Error: library dir does not exist: D:/projects/webcam/node_modules/opencv-build/opencv/build/lib/Release`

# Auto Build - Full Error Log
npm install --save opencv4nodejs
npm WARN cleanup Failed to remove some directories [
npm WARN cleanup   [
npm WARN cleanup     'D:\\projects\\webcam\\node_modules',
npm WARN cleanup     [Error: EBUSY: resource busy or locked, rmdir 'D:\projects\webcam\node_modules\opencv-build'] {
npm WARN cleanup       errno: -4082,
npm WARN cleanup       code: 'EBUSY',
npm WARN cleanup       syscall: 'rmdir',
npm WARN cleanup       path: 'D:\\projects\\webcam\\node_modules\\opencv-build'
npm WARN cleanup     }
npm WARN cleanup   ]
npm WARN cleanup ]
npm ERR! code 1
npm ERR! path D:\projects\webcam\node_modules\opencv4nodejs
npm ERR! command failed
npm ERR! command C:\WINDOWS\system32\cmd.exe /d /s /c node ./install/install.js
npm ERR! info install using lib dir: D:/projects/webcam/node_modules/opencv-build/opencv/build/lib/Release
npm ERR! D:\projects\webcam\node_modules\opencv4nodejs\install\install.js:37
npm ERR!   throw new Error('library dir does not exist: ' + libDir)
npm ERR!   ^
npm ERR!
npm ERR! Error: library dir does not exist: D:/projects/webcam/node_modules/opencv-build/opencv/build/lib/Release
npm ERR!     at Object.<anonymous> (D:\projects\webcam\node_modules\opencv4nodejs\install\install.js:37:9)
npm ERR!     at Module._compile (node:internal/modules/cjs/loader:1097:14)
npm ERR!     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1149:10)
npm ERR!     at Module.load (node:internal/modules/cjs/loader:975:32)
npm ERR!     at Function.Module._load (node:internal/modules/cjs/loader:822:12)
npm ERR!     at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
npm ERR!     at node:internal/main/run_main_module:17:47
npm ERR!
npm ERR! Node.js v17.3.0

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\<MY_USER>\AppData\Local\npm-cache\_logs\2022-01-03T14_55_06_355Z-debug-0.log

*OpenCV version* : 5.6.0

*With OpenCV-contrib?* (extra modules): no

*OS*: Windows 10

**Comment by liudonghua123** [comment]
I have the same problems.

```shell
C:\Users\Liu.D.H>npm i -g opencv4nodejs
npm WARN cleanup Failed to remove some directories [
npm WARN cleanup   [
npm WARN cleanup     'C:\\Users\\Liu.D.H\\AppData\\Roaming\\npm\\node_modules\\opencv4nodejs',
npm WARN cleanup     [Error: EBUSY: resource busy or locked, rmdir 'C:\Users\Liu.D.H\AppData\Roaming\npm\node_modules\opencv4nodejs\node_modules\opencv-build'] {
npm WARN cleanup       errno: -4082,
npm WARN cleanup       code: 'EBUSY',
npm WARN cleanup       syscall: 'rmdir',
npm WARN cleanup       path: 'C:\\Users\\Liu.D.H\\AppData\\Roaming\\npm\\node_modules\\opencv4nodejs\\node_modules\\opencv-build'
npm WARN cleanup     }
npm WARN cleanup   ],
npm WARN cleanup   [
npm WARN cleanup     'C:\\Users\\Liu.D.H\\AppData\\Roaming\\npm\\node_modules\\opencv4nodejs',
npm WARN cleanup     [Error: EBUSY: resource busy or locked, rmdir 'C:\Users\Liu.D.H\AppData\Roaming\npm\node_modules\opencv4nodejs\node_modules\opencv-build'] {
npm WARN cleanup       errno: -4082,
npm WARN cleanup       code: 'EBUSY',
npm WARN cleanup       syscall: 'rmdir',
npm WARN cleanup       path: 'C:\\Users\\Liu.D.H\\AppData\\Roaming\\npm\\node_modules\\opencv4nodejs\\node_modules\\opencv-build'
npm WARN cleanup     }
npm WARN cleanup   ]
npm WARN cleanup ]
npm ERR! code 1
npm ERR! path C:\Users\Liu.D.H\AppData\Roaming\npm\node_modules\opencv4nodejs
npm ERR! command failed
npm ERR! command C:\Windows\system32\cmd.exe /d /s /c node ./install/install.js
npm ERR! info install using lib dir: C:/Users/Liu.D.H/AppData/Roaming/npm/node_modules/opencv4nodejs/node_modules/opencv-build/opencv/build/lib/Release
npm ERR! C:\Users\Liu.D.H\AppData\Roaming\npm\node_modules\opencv4nodejs\install\install.js:37
npm ERR!   throw new Error('library dir does not exist: ' + libDir)
npm ERR!   ^
npm ERR!
npm ERR! Error: library dir does not exist: C:/Users/Liu.D.H/AppData/Roaming/npm/node_modules/opencv4nodejs/node_modules/opencv-build/opencv/build/lib/Release
npm ERR!     at Object.<anonymous> (C:\Users\Liu.D.H\AppData\Roaming\npm\node_modules\opencv4nodejs\install\install.js:37:9)
npm ERR!     at Module._compile (node:internal/modules/cjs/loader:1101:14)
npm ERR!     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
npm ERR!     at Module.load (node:internal/modules/cjs/loader:981:32)
npm ERR!     at Function.Module._load (node:internal/modules/cjs/loader:822:12)
npm ERR!     at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
npm ERR!     at node:internal/main/run_main_module:17:47

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Liu.D.H\AppData\Local\npm-cache\_logs\2022-01-04T07_44_59_085Z-debug-0.log

C:\Users\Liu.D.H>
```

**Comment by SuperSchek** [comment]
Experiencing the same issue on MacOS using node version `16.13.1`.

**Comment by UrielCh** [comment]
what's are the error message using:
```

**Comment by moontai0724** [comment]
In my situation, the root cause is that it cannot auto build (or even install) the `opencv-build` package.

When I try to install `opencv-build` by executing `npm i opencv-build`, it stucked on `reify:... Completed in XXXms`, then I found [this thread](https://stackoverflow.com/questions/66893199).

After downgrade npm by `npm i -g npm@6`, then try again, everything works like a charm.

**Comment by jazozaya** [comment]
I was having issues with this as well. Downgrading to Node 14 worked for me.

**Comment by tekisrinivas20** [comment]
> In my situation, the root cause is that it cannot auto build (or even install) the `opencv-build` package.
> 
> When I try to install `opencv-build` by executing `npm i opencv-build`, it stucked on `reify:... Completed in XXXms`, then I found [this thread](https://stackoverflow.com/questions/66893199).
> 
> After downgrade npm by `npm i -g npm@6`, then try again, everything works like a charm.

Thanks for the information, I also faced the same issue, and it worked after downgrading the npm version to 6

**Comment by UrielCh** [comment]
Hi,
Great news for those people that do not want to build their OpenCV:
I published @u4/opencv4nodejs V 6.2.4 today,

This version autodetects the common setup path for Brew on Mac, Chocolatey on Windows, and Apt on Linux.

- Windows: 
> choco install opencv

- Mac: 
> brew install opencv

- debian:
> apt -y install libopencv-contrib-dev libopencv-dev

just define environment variable: OPENCV4NODEJS_DISABLE_AUTOBUILD=1

And your prebuild OpenCV will be used.

You may need to call:
`npx build-opencv rebuild`
or
`npx build-opencv --nobuild rebuild` (if you do not define OPENCV4NODEJS_DISABLE_AUTOBUILD variable)

**Comment by dids-reyes** [comment]
> npm i -g npm@6

tried this and i got pass the error `library dir does not exist`

but im getting this error now
```
[ 50%] Built target libprotobuf
make: *** [all] Error 2

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! opencv-build@0.1.9 install: `node ./install.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the opencv-build@0.1.9 install script.
```

**Comment by Idealyy** [comment]
> Please try that : in am admin power shell
> 
> ```shell
> choco install cmake -y
> ```
> 
> in you user cmd / powershell
> 
> ```shell
> cd D:\projects\webcam
> npm i -g node-gyp
> npm i @u4/opencv4nodejs
> echo build nodejs
> node .\node_modules\.bin\build-opencv --help
> node .\node_modules\.bin\build-opencv --version 4.5.4 build
> ```
> 
> The errors messages of this version are way cleaner, and the build should works fine with nodeJS 16
> 
> PS: do not use 4.5.5 on MacOS. PS: the original version do not work with Visual Studio 2019.

Hi i 'm havi,g issues installing @u4/opencv4nodejs. And i tried following these step but it doesn't work. 

npm error code 1
npm error path D:\learnnode\node_modules\@u4\opencv4nodejs
npm error command failed
npm error command C:\Windows\system32\cmd.exe /d /s /c node-gyp rebuild
npm error gyp info it worked if it ends with ok
npm error gyp info using node-gyp@10.2.0
npm error gyp info using node@22.9.0 | win32 | x64
npm error gyp info find Python using Python version 3.9.0 found at "C:\Users\ideal\AppData\Local\Programs\Python\Python39\python.exe"
npm error gyp http GET https://nodejs.org/download/release/v22.9.0/node-v22.9.0-headers.tar.gz
npm error gyp http 200 https://nodejs.org/download/release/v22.9.0/node-v22.9.0-headers.tar.gz
npm error gyp http GET https://nodejs.org/download/release/v22.9.0/SHASUMS256.txt
npm error gyp http GET https://nodejs.org/download/release/v22.9.0/win-x64/node.lib
npm error gyp http 200 https://nodejs.org/download/release/v22.9.0/SHASUMS256.txt
npm error gyp http 200 https://nodejs.org/download/release/v22.9.0/win-x64/node.lib
npm error gyp info find VS using VS2022 (17.11.35312.102) found at:
npm error gyp info find VS "C:\Program Files\Microsoft Visual Studio\2022\Community"
npm error gyp info find VS run with --verbose for detailed information
