### ISSUE TITLE
[!] RollupError: Could not resolve "../build/Release/opencv4nodejs.node" from "../build/Release/opencv4nodejs.node?commonjs-external"

### ISSUE THREAD

**Issue by charleslongzaifan** [justadudewhohacks/opencv4nodejs#857]
RollupError: Could not resolve "../build/Release/opencv4nodejs.node" from "../build/Release/opencv4nodejs.node?commonjs-external"
    at error (E:\project\pxingLabelTool\client\node_modules\_rollup@3.2.3@rollup\dist\shared\rollup.js:206:30)
    at ModuleLoader.handleInvalidResolvedId (E:\project\pxingLabelTool\client\node_modules\_rollup@3.2.3@rollup\dist\shared\rollup.js:23120:24)
    at E:\project\pxingLabelTool\client\node_modules\_rollup@3.2.3@rollup\dist\shared\rollup.js:23083:26
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)

**Comment by UrielCh** [comment]
no context, no detail....
